### ISSUE TITLE
Private channels inaccessible

### ISSUE THREAD

**Issue by duncan-bayne** [yuya373/emacs-slack#101]
I've connected successfully to our work Slack account, and can join and use public channels.

However, despite a private channel `private1` being listed here:

```
(slack-register-team
 :name "work"
 :default t
 :client-id "1234"
 :client-secret "5678"
 :token "9012"
 :subscribed-channels '(public1 public2 private1))
```

... I can't join said private channel using `M-x slack-select-channel`; it doesn't appear in the autocomplete list, and can't be entered manually.

**Comment by yuya373** [comment]
use `slack-group-select` or `slack-select-rooms`
