### ISSUE TITLE
IDO mode support for selecting slack teams/channels

### ISSUE THREAD

**Issue by hilldr** [yuya373/emacs-slack#102]

**Comment by rpdillon** [comment]
FWIW, [Ivy](https://github.com/abo-abo/swiper) works well with team/channel/IM selection.

**Comment by hilldr** [comment]
It turns out that [ido-ubiquitous](https://github.com/DarwinAwardWinner/ido-ubiquitous) fixes this perfectly. I now have IDO for selecting teams, channels, and users.

```elisp
(use-package ido-ubiquitous
  :init
  (ido-ubiquitous-mode 1))
