### ISSUE TITLE
Emacs freeze frequently

### ISSUE THREAD

**Issue by aki2o** [yuya373/emacs-slack#103]
When I do other works with opening some slack channels, Emacs freeze with high-consumption of cpu and memory frequently.
It seems to happen with overlay function like `isearch-forward` but I'm not sure.

At present, all I can do is to send SIGKILL to a Emacs process when this trouble happens.
Could you give me some help to find the cause?

英語に自信無いので、補足します。
頻繁にフリーズしてしまう感じで、どうもOverlay関連の機能を使うと起こる気がしていますが、確証はないです。
起きると、Emacs強制終了するしか無くて、今のところ原因が全然わかりません。
何とか原因を特定したいのですが、ログを出力する方法とか、この辺が怪しそうとか、何か情報頂けませんでしょうか。

環境は以下です。
MacBookPro OS X 10.11.5
GNU Emacs 24.5.1 (x86_64-apple-darwin15.5.0, NS apple-appkit-1404.47) of 2016-07-03 on aki2o-no-MacBook-Pro.local

**Comment by FrancisMurillo** [comment]
I have the same problem, thus I open slack in a separate frame to close it without fear. Over time there is a memory issue for me.

**Comment by DamienCassou** [comment]
Emacs regularly freezes for a few seconds and then comes back to life (sometimes I help it with `C-g`). Not starting slack seems to fix the problem. Could it be that slack has a hard time processing data from the server and freezes Emacs while doing so because it's all single threaded?
