### ISSUE TITLE
persistent notification

### ISSUE THREAD

**Issue by vspinu** [yuya373/emacs-slack#104]
I have hard time figuring how to make persistent notifications. 

In jabber if new message arrived I will get a highlighted sender name in mode-line till I visit that buffer. This is very convenient. How can I achieve similar behavior with slack?

My configuration of alert is `(setq alert-default-style 'mode-line)`. All I see is a temporary highlight of mode-line which disappars on any user action.

**Comment by ryuslash** [comment]
Do you use powerline or something else? Since Slack chat buffers are based on Circe's lui library the persistent notifications should appear in the mode line automatically thanks to Circe's tracking library. Normally this will show a shortened version of the buffer name in the mode line.

**Comment by vspinu** [comment]
> Do you use powerline or something else? 

No, I don't.

> should appear in the mode line automatically thanks to Circe's tracking library. Normally this will show a shortened version of the buffer name in the mode line.

I see the whole mode line highlighted in an ugly salad bright green color which either disappears on any user action, or stays there forever till I close emacs. I will investigate these issues at some point but it's a bit tricky because there are so many different moving components. 

How do you actually jump to the circle buffer that demands attention?  Thanks.

**Comment by ryuslash** [comment]
> How do you actually jump to the circle buffer that demands attention? Thanks.

There is the command `tracking-next-buffer`, which bound to `C-c C-@` and `C-c C-SPC` on my system.
