### ISSUE TITLE
Rooms with unread messages / notifications

### ISSUE THREAD

**Issue by jlee-made** [yuya373/emacs-slack#112]
Slack's web UI shows which rooms have unread messages, and also which have unseen notifications.

Is there a way to do either of these in emacs-slack?

If not, please consider this a feature request.

Thanks for emacs-slack!

**Comment by yuya373** [comment]
emacs-slack also show which room have unread messages like blow

![2016-09-24 13 44 21](https://cloud.githubusercontent.com/assets/3055271/18806158/45163e4e-825d-11e6-9182-27fabe95bf61.png)

I don't understand unseen notification, please tell me details.

**Comment by jlee-made** [comment]
With 20160928.2036 (which I guess is from melpa), I see the * markers against some rooms in `slack-select-rooms`, but they are present even for rooms that don't have unread messages.  Also, some rooms that have unread messages don't have * markers next to them.

Maybe I misunderstand what a read message is for emacs-slack?

By unseen notification, I mean that the slack web UI shows an indicator in red when it issues a notification.  Perhaps this is not part of the slack API, or intended to be separate from emacs-slack?  Because the notification configuration model in the slack UI is done well in my opinion, it would be nice to see it reflected in emacs-slack.

**Comment by yuya373** [comment]
In above screenshot, `*` means the user is online and marked only direct message, `(1)` means direct message with potato has one unread message.

**Comment by stevenmccord** [comment]
👍  on this one.  By having the ability to view which messages were based on a mention or a highlighted word that you setup in slack would be nice vs. just activity in a room.  I utilize the unread rooms but that doesn't delineate whether it was a mention or highlighted word.  Or maybe there is another way to achieve this.  Thanks for the client!
