### ISSUE TITLE
Send formatted links from emacs slack client?

### ISSUE THREAD

**Issue by cswarth** [yuya373/emacs-slack#113]
The slack [message API](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22I%20am%20a%20test%20*message*%3A%20%3Chttp%3A%2F%2Fwww.example.com%7Csome%20link%3E%22%7D) (but not the slack GUI clients) allow you to send a message with a formatted link, e.g. 
```
{
    "text": "I am a test *message*:<http://www.example.com|some link>"
}
```
Which shows up as "I am a test ﻿⁠⁠⁠**message**﻿⁠⁠⁠: [some link](http://www.example.com)"

When I send the same message via the emacs slack client, I get,
 `I am a test message:<http://www.example.com|some link>`
where the word `message` is in bold, but the link is not active and shows the formatting characters.

Is there any way to send a formatted link via the slack emacs client?

**Comment by cswarth** [comment]
To follow up, I thought the fault might lie with some of the text transformations done in `slack-escape-message` or in `json-encode`.  The former translates '<' and '>' to '&lt;' and '&gt;'.  `json-encode` escapes '/' to '\/'.  

Removing the transformation done by both those routines however did not allow me to post a formatted link to slack.  I confirmed that the json that was being sent to the server looks like the json in the  [message API example](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22I%20am%20a%20test%20*message*%3A%20%3Chttp%3A%2F%2Fwww.example.com%7Csome%20link%3E%22%7D), but still no-go.

**Comment by yuya373** [comment]
I think websocket client can't  send complex formatted messages. 
please try slack web client which using websocket to send message.
