### ISSUE TITLE
Slack Websocket PING Timeout.

### ISSUE THREAD

**Issue by cro** [yuya373/emacs-slack#119]
I have installed emacs-slack with the slack layer in Spacemacs, Emacs 25.1.1.  Emacs-slack reports that the websocket is initialized successfully and I am also able to grab the initial JSON with a curl command & my access token.  However, when executing slack-start I get:

```
Slack Websocket Is Ready! - {team name redacted}
Error running timer: (wrong-type-argument hash-table-p (slack-ws-init-ping-check-timers)) [3 times]
Slack Websocket PING Timeout.
```

Suggestions?

Thanks.

My configuration (sanitized), currently in .spacemacs, looks like this:

```
  (setq slack-buffer-emojify t) ;; if you want to enable emoji, default nil
  (setq slack-prefer-current-team t)
  (setq alert-default-style 'notifier)
  (slack-register-team
   :name "{redacted}"
   :default t
   :client-id "{id from slack app config}"
   :client-secret "{secret}"
   :token "xoxp-XXX"
   :subscribed-channels '(general)
  )
  (evil-define-key 'normal slack-info-mode-map
    ",u" 'slack-room-update-messages)
  (evil-define-key 'normal slack-mode-map
    ",c" 'slack-buffer-kill
    ",ra" 'slack-message-add-reaction
    ",rr" 'slack-message-remove-reaction
    ",rs" 'slack-message-show-reaction-users
    ",pl" 'slack-room-pins-list
    ",pa" 'slack-message-pins-add
    ",pr" 'slack-message-pins-remove
    ",mm" 'slack-message-write-another-buffer
    ",me" 'slack-message-edit
    ",md" 'slack-message-delete
    ",u" 'slack-room-update-messages
    ",2" 'slack-message-embed-mention
    ",3" 'slack-message-embed-channel
    "\C-n" 'slack-buffer-goto-next-message
    "\C-p" 'slack-buffer-goto-prev-message)
  (evil-define-key 'normal slack-edit-message-mode-map
    ",k" 'slack-message-cancel-edit
    ",s" 'slack-message-send-from-buffer
    ",2" 'slack-message-embed-mention
    ",3" 'slack-message-embed-channel)

**Comment by cro** [comment]
I should note that I have tried with two different teams, one that requires 2FA, one that does not.

**Comment by cro** [comment]
Closing, appears this was a transient error.  Sorry for the noise.

**Comment by wallacewinfrey** [comment]
I'm getting this issue.

**Comment by rgrinberg** [comment]
Getting this issue as well.

**Comment by cro** [comment]
I just re-opened it, though I'm not sure if this is on Slack's side or not.

**Comment by zvbuhl** [comment]
Me too — driving me crazy with the `*Warnings*` pop-up.

**Comment by zvbuhl** [comment]
I think I've tracked it down: apparently it's possible to have slack messages without bodies; `slack-message-notify-alert` performs a `string-match` against the message body, which of course throws an error when passed nil. Patch forthcoming.

**Comment by swaroopch** [comment]
Experiencing the same:

```
Error running timer: (wrong-type-argument hash-table-p (slack-ws-init-ping-check-timers))
[2016-10-26 07:34:10] Slack Websocket PING Timeout. - <team name>
```

#### Spacemacs System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.4
- Spacemacs branch: develop (rev. cdcf707)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
                 csv django emacs-lisp git github
                 (go :variables go-use-gometalinter t)
                 helm html javascript markdown
                 (org :variables org-enable-github-support t org-enable-bootstrap-support t)
                 osx python
                 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
                 slack sql syntax-checking version-control yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by yuya373** [comment]
@swaroopch thanks for information. Could you tell me this package's version?

**Comment by swaroopch** [comment]
@yuya373 Under `~/.emacs.d/elpa`, I have `slack-20161025.1912` directory. I'm assuming that is the version? :)

**Comment by swaroopch** [comment]
@yuya373 Please let me know anyway I can assist in debugging the issue.

**Comment by yuya373** [comment]
@swaroopch thanks! that is! please execute`toggle-debug-on-error` and print stack trace here.

**Comment by swaroopch** [comment]
@yuya373  After `SPC t D` in Spacemacs, I immediately got:

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p (slack-ws-init-ping-check-timers))
  puthash("1477495170.002821" [nil 22544 51606 3223 nil #[0 "\301\300!\207" ["T024FBX85" slack-ws-ping-timeout] 2] nil nil 0] (slack-ws-init-ping-check-timers))
  slack-ws-set-check-ping-timer([eieio-class-tag--slack-team ... <team details>])
```

**Comment by yuya373** [comment]
@swaroopch thanks it helps. I think slack-team's :initform slot option is not evaluated in this case.

**Comment by yuya373** [comment]
this will fix in next melpa release or HEAD on master branch.
if not reopen this issue.

**Comment by swaroopch** [comment]
@yuya373 That fixed it! Thank you for an amazing package and for listening to issues :)
