### ISSUE TITLE
Can I scroll to bottom after jumping to a DM / channel?

### ISSUE THREAD

**Issue by swaroopch** [yuya373/emacs-slack#128]
I'm trying `(advice-add 'slack-buffer-function :after 'end-of-buffer)` but that doesn't seem to work.

I couldn't find any hooks as well.

Thanks!

**Comment by yuya373** [comment]
`slack-buffer-function`is a variable, default value is`switch-to-buffer-other-window` and used to open buffer in this package.
so, you can chage default behavior with your own function.

**Comment by swaroopch** [comment]
Thanks for the hint, will investigate.
