### ISSUE TITLE
How do I start it?

### ISSUE THREAD

**Issue by ironchicken** [yuya373/emacs-slack#133]
I've created a client ID and token. I then customised the `slack-client-id`, `slack-client-secret`, and `slack-token` variables. But how do I actually get into my channels? If I do `M-x start-slack` it asks for me a team name and then client ID. But I've already provided the client ID as a customisation! And why would I have to give my team name every time I start? Perhaps `start-slack` is the wrong command?

I installed from `el-get` but I didn't copy any of the config in the README as I didn't understand it and most of it looked like it was just related to setting up keybindings.

Any pointers how to get started?

**Comment by jgkamat** [comment]
I would suggest using the guide in the readme:
```
  (slack-register-team
   :name "emacs-slack"
   :default t
   :client-id "aaaaaaaaaaa.00000000000"
   :client-secret "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
   :token "aaaa-sssssssssss-88888888888-hhhhhhhhhhh-jjjjjjjjjj"
   :subscribed-channels '(test-rename rrrrr))
```
After setting this up, slack-start should work without any prompts.

**Comment by ironchicken** [comment]
Thanks, this is a bit clearer now.
