### ISSUE TITLE
Emacs 25 Support

### ISSUE THREAD

**Issue by jgkamat** [yuya373/emacs-slack#134]
For me, emacs-slack seems to work just fine in emacs24, but breaks in emacs25. In emacs25, connection appears to happen just fine, but when I try and send a message to a channel, I get:

```
[2016-11-05 00:26:37] Slack Websocket Try To <TeamName> 0/360 - <TeamName>
[2016-11-05 00:26:37] Slack Websocket is not open - <TeamName>
Slack Authorization Finished - <TeamName>
```

And no message is posted. This causes all the slack buffers to get deleted (loss of connection). Anyone else seeing this issue?

**Comment by duncan-bayne** [comment]
Seems fine for me in Emacs 25.1.1.

**Comment by jgkamat** [comment]
Hmm, thats weird, I'm getting this on 25.1.1, maybe this is a weird combination of my environment and emacs25. I have no idea what would cause this though...

**Comment by jgkamat** [comment]
Yah, on my arch install emacs-slack works just fine, but on debian it dosen't seem to work. Maybe I'm missing some dependencies somewhere...

**Comment by jgkamat** [comment]
This turned out to be a weird configuration issue with me turning on gnutls-verify-error and a bunch of other things. Not sure why it was only showing up on emacs25 though. I doubt it is related to this package, so closing.
