### ISSUE TITLE
Possibly broken MELPA dependencies?

### ISSUE THREAD

**Issue by FinnG** [yuya373/emacs-slack#147]
I installed emacs-slack through MELPA, and I've set up my client ID and secret, as well as my token. When I run `slack-im-select` and select a group and message from the list, I get the following error:

`slack-buffer-insert: Symbol’s function definition is void: lui-insert-with-text-properties`

Sure enough, I can see in slack-buffer.el that the `lui-insert-with-text-properties` function is called in `slack-buffer-insert`.  Running `describe function lui-insert-with-text-properties` confirms that this symbol isn't defined in my Emacs, which is GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-09-20.

A bit of looking around reveals that this was added to the lui library in circe on 4-Nov-2016 (https://github.com/jorgenschaefer/circe/pull/270/files). I'm guessing the version of circe in MELPA that was pulled down when I installed it isn't new enough to contain this function? My `circe-version` is 2.3. Looking in lui.el confirms that I don't have this patch applied.

**Comment by FinnG** [comment]
So I ran a test and overwrote my lui.el with the latest version from the repo (yuck!) and it worked.

I'm not sure whether this is a problem at your end, or circe's? I'm not familiar with how Emacs' package system works.

**Comment by ryuslash** [comment]
Hi @FinnG,

MELPA's latest Circe version is 20170107.632, so it was last pulled down on Januari 7th of 2017, which is long after November 4th of 2016. It sounds like either you haven't updated your packages in a while or maybe you're using melpa stable or something, is that possible?

**Comment by FinnG** [comment]
Sorry, I should have mentioned that I'm using MELPA regular not MELPA stable. If I look up the Circe package then I see the following:
 ```
Version: 20170107.632
Summary: Client for IRC in Emacs
Requires: cl-lib-0.5
Required by: slack-20170111.732
Homepage: https://github.com/jorgenschaefer/circe
Other versions: 20160608.1315 (installed).```

Which is interesting, because it knows that the version I have isn't the most up to date one... I explicitly installed Circe through MELPA and it works fine. I'm still not sure why when I installed emacs-slack I didn't end up with the latest version? Anyway, after grabbing the latest version I'm up and running, so happy for this to be closed. Also happy to help look into this issue further if you're interested in what's going on.

Thanks for your help.

**Comment by ryuslash** [comment]
Well packages don't update themselves automatically. You have to tell Emacs to upgrade them. And since 20160608.1315 is a larger version number than 2.3, emacs-slack doesn't know it needs a newer version. We can't depend on a version greater than 20160608.1315 either since that will break support for melpa stable.

When you're using melpa I think it's a good idea to keep your packages up-to-date.
