### ISSUE TITLE
`slack-file-upload` is behaves like a no op

### ISSUE THREAD

**Issue by drwebb** [yuya373/emacs-slack#152]
Calling `slack-file-upload` in a normal file buffer doesn't do anything or print anything in the message buffer. When execute the function it open a minibuffer containing a list of slack channels in my team. After I select a channel, it just loops and opens the same list in the minibuffer. `Ctrl-G` is the only way to escape the channel select loop.

I am attempting to upload a file in an emacs buffer to a slack channel, so I though this function would have this behavior. Other file commands also didn't work for me, but perhaps those reports should be saved for other issues.

**Comment by christianramet** [comment]
Hi,

Having the same exact issue with slack-file-upload: looping into the channel list.

**Comment by yuya373** [comment]
input empty string can be exit loop.
if you use helm <kbd>C</kbd> + <kbd>RET</kbd> or <kbd>M</kbd> + <kbd>RET</kbd>.
files can be uploaded to multiple channels, select loops.

**Comment by christianramet** [comment]
Many thanks. That was it @yuya373. And I was indeed using helm, should have precised.

**Comment by jgkamat** [comment]
I think that there should be an option to prevent looping (most of the time, I would like to upload a file to only a single channel). It probably wouldn't be too hard to add too...

**Comment by fomentia** [comment]
I was confused by the looping behaviour, too! I think it's fine, but there should be some explanation before entering the loop (E.G. "input empty string to finish channel selection").

Otherwise, great work on this app @yuya373! I'm loving it!

**Comment by duncan-bayne** [comment]
Note that if you're using Ivy, not Helm, the default empty string command is `C-M-j`.
