### ISSUE TITLE
slack-group-list-update errors with: slack-room-list-update: Keyword argument nil not one of (:sync)

### ISSUE THREAD

**Issue by com4** [yuya373/emacs-slack#157]
When running `slack-group-list-update` I get the error:

`slack-room-list-update: Keyword argument nil not one of (:sync)`

 - `slack-im-list-update` and `slack-channel-list-update` both work fine.
 - My config is modeled after the config in the README.

**Comment by com4** [comment]
This has been fixed in the latest release

**Comment by com4** [comment]
nm. wrong method tested.

**Comment by yuya373** [comment]
@com4 #162 will fix this issue. thanks for reporting!
