### ISSUE TITLE
websocket-1.5 is unavailable

### ISSUE THREAD

**Issue by least-olegs** [yuya373/emacs-slack#16]
```
Warning (emacs): Unable to activate package `slack'.
Required package `websocket-1.5' is unavailable
```
If I use the setup from the readme.

I can load this package with ELPA, but then there are many other errors possibly related to this.

Actually, `el-get` isn't able to install any of the required versions except for `circle` package.

**Comment by yuya373** [comment]
I forget to update README.
now melpa repository is available, you only need to `(el-get-bundle slack)` I think.
