### ISSUE TITLE
REQUEST [error] Error (timeout) while connecting to https://slack.com/api/rtm.start.

### ISSUE THREAD

**Issue by fomentia** [yuya373/emacs-slack#161]
I get this error when calling `slack-start` in Emacs 25.1.1 on the latest version of Windows 10. My slack config is as follows (sensitive data redacted):

```
(slack-register-team (quote :name) "Slack Team"
                     (quote :client-id) "1010101010.121212121212"
                     (quote :client-secret) "asdf123456789asdfjklpoiu1234"
                     (quote :token) "bobj-1010101010-1010101010-121212121212-asdf123456789asdfjklpoiu1234asdfgha")
```

**Comment by jvillasante** [comment]
I also get the same error: 

```
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to https://slack.com/api/rtm.start. [2 times]
```

**Comment by jvillasante** [comment]
Ok, it seems that is something related to a slow connection. The default timeout (5) is too low.
Adding `(setq slack-request-timeout 15)` solves the problem with the default `request-backend` of `curl` that is a lot better because it's the only one that supports file uploads.

Great work BTW!! Thanks!!

**Comment by fomentia** [comment]
@jvillasante Even with a timeout of 15 seconds, it gives me the same exception. And it's not a problem with slow internet; I have AT&T fiber (900 MB/s - 1 GB/s).

**Comment by agzam** [comment]
for some reason I'm unable to reliably use the package. 
- I can't select a channel unless `request-backend` set to `url-retrieve` (it's slow but, works)
- even with that, after jumping to a channel it doesn't show all the latest messages, it cuts off on a previous day, although there are definitely more messages in the channel (I can see them in web client and Slack app)

**Comment by mgallego** [comment]
I have the same problem, but only in one team with a big amount of users, maybe the problem could be related with the number of users, channels, whatever than create a big amount of data or a big request time.

I set 500 as timeout and the problem disappears, with for example 120 the problem remains.

I see too, than the slack web client is very slow loading this team, very slow.
