### ISSUE TITLE
Failed to request slack-authorize: missing_scope

### ISSUE THREAD

**Issue by Malabarba** [yuya373/emacs-slack#163]
Hi there,

First of all, thanks for creating this package.

I'm trying to follow the setup instructions, but I'm getting the following message when I try to `slack-start`:

    Failed to request slack-authorize: missing_scope

I have a feeling that slack has changed this stuff recently, because the screenshots provided in the README do not match the actual pages that are linked there.

For instance the link https://api.slack.com/applications/new is completely different from the screenshot. While I could use the screenshot as a guideline, the page I got also asked me to choose all authorization scopes the app needed, and there's no mention of that in the README.
I tried choosing most of the scopes available, and that allowed to me to install the app in my team's Slack, which then gave me a token (see the screen below). 
![token-example](https://cloud.githubusercontent.com/assets/453029/23520107/4ba696c8-ff58-11e6-82e5-0df5a47383e3.jpg)

Then I tried providing this token in `slack-register-team`, but when I call `slack-start` I get the message quoted above.

**Comment by yuya373** [comment]
Hi! I updated [README](https://github.com/yuya373/emacs-slack/blob/master/README.md#how-to-get-token). try this.

**Comment by Malabarba** [comment]
Yep, working now. Thanks!
