### ISSUE TITLE
Failed to request slack-authorize: missing_scope

### ISSUE THREAD

**Issue by munk** [yuya373/emacs-slack#165]
I'm trying to set up emacs to work with my existing slack team.

When I try to run `slack-start` or `slack-register-team` I get the following error message: 
`Failed to request slack-authorize: missing_scope`

The README mentions which scopes are required, which I've set up in my app permissions. 

What am I misunderstanding?

**Comment by Malabarba** [comment]
Are you providing the token in `slack-register-team`? I was doing that at first, but you're actually **NOT** supposed to do that the first time you call the function.

**Comment by munk** [comment]
I was. I try it again without the token, I don't see any errors. But when I call slack-start now, I see an error `Failed to request slack-authorize: not_authed`. What is the step after `slack-register-team` supposed to be?
