### ISSUE TITLE
Is it possible to remove the "  Team - " prefix when completing channel name?

### ISSUE THREAD

**Issue by Malabarba** [yuya373/emacs-slack#166]
Thanks again for helping me with the token issue.

Now... I only use slack.el for one team, and it's annoying to have to hit `tab` everytime I wanna switch channel/group in order to complete that initial `  Team - ` prefix. Is there a way to remove the prefix from the channel names?

**Comment by Malabarba** [comment]
Shortening the buffer names would also make the buffers take up less space on the mode-line. Currently they take up a lot, even though `tracking.el` tries to minimize them.

**Comment by Malabarba** [comment]
Alternatively, one could make the `completing-read` function configurable. For instance, Replacing it with `ido-completing-read` makes it much more pleasant to switch channels (and more in-line with the web interface).

**Comment by yuya373** [comment]
added custom variable to hide team name in #168 .

**Comment by yuya373** [comment]
and added custom variable to configure completing read function in #169
