### ISSUE TITLE
Last read functionality? 

### ISSUE THREAD

**Issue by Malabarba** [yuya373/emacs-slack#167]
By looking through the code, I see several references to things like `mark-last-read`. Does this mean that there's already some built in functionality for keeping track of which messages I've read and which are new? 

I couldn't find anything about it on the readme. 

Thanks

**Comment by yuya373** [comment]
> keeping track of which messages I've read and which are new?

Yes. this function using `last-read` to fetch new messages.
https://github.com/yuya373/emacs-slack/blob/develop/slack-room.el#L216
