### ISSUE TITLE
List of unreads messages?

### ISSUE THREAD

**Issue by piotr-yuxuan** [yuya373/emacs-slack#175]
Hiya, thanks a lot for this Slack integration into Emacs! 😄 

I've been using it for a couple of days and it's great but I haven't found any (obvious) ways to get a list of channels/im/rooms/groups I've subscribed to which contains new messages I haven't read. 

Would you know how to get this information with current `emacs-slack` version? or would it be hard to develop? If it's a newbie-friendly task, I'd like to give a try!

**Comment by yuya373** [comment]
`slack-select-rooms` display list of channels/ims/groups and unread messages count. like `baz-channel (3)`. there is 3 messages unread in baz-channel.
`slack-select-channels`, `slack-select-ims`, `slack-select-groups` display same way.

currently, there is no "All Unreads" function like Slack App.

**Comment by FrancisMurillo** [comment]
Would it be possible then to have a command that lists all unread channels, rooms, ims and groups together? Perhaps, a command to switch to the next unread channel, room or ims as with `previous-buffer` or `next-buffer`.

I tried hacking for the unread rooms but it may not be performant. This to say I am interested in a quicker workflow to read team messages.

**Comment by yuya373** [comment]
@FrancisMurillo 
```emacs-lisp
(defun slack-select-unread-rooms ()
  (interactive)
  (let ((team (slack-team-select)))
    (slack-room-select
     (cl-loop for team in (list team)
              append (with-slots (groups ims channels) team
                       (cl-remove-if #'(lambda (room) (not (< 0 (oref room unread-count-display))))
                                     (append ims groups channels)))))))
```
this command list unread ims, groups and channels together. Is this useful?

**Comment by FrancisMurillo** [comment]
@yuya373 Thank you good sir. This looks promising. I will field test this later.

**Comment by yuya373** [comment]
I added `slack-select-unread-rooms` in 83c36fb, close this issue.

**Comment by benthamite** [comment]
`slack-select-unread-rooms` is showing unread channel threads, but not unread direct messages. Is anyone else experiencing this?
