### ISSUE TITLE
Intermittent websocket connection failures

### ISSUE THREAD

**Issue by benjamreynolds** [yuya373/emacs-slack#180]
My websocket connections dont appear to be super stable. Some days I can use emacs as my main slack client all day, and others I am completely unable to get it to connect. My configuration doesnt change from day to day either. I would love some assistance figuring out what I am doing wrong if anything or if there is some sort of bug. 

I have turned on `debug-on-error` before running `slack-start` but get such a large stack trace that the size of the buffer causes emacs to slow down and even freeze occasionally. The beginning of which looks like this...
```
Debugger entered--Lisp error: (unbound-slot slack-team "#<slack-team slack-team>" ims oref)
  signal(unbound-slot (slack-team "#<slack-team slack-team>" ims oref))

```

FWIW, I have two teams configured. One of which only shows up in my list of slack teams when the websocket connection is succesful, the other always appears. Team-2, the one that always appears, will successfully receive new messages in channels I have open, and new channels will appear when created, but I cannot send messages from it. My messages buffer looks like this..

Run `slack-start`
```
Slack Authorization Finished - team-2
Slack Authorization Finished - team-1
```
Attempt to send a message in a channel on team-2
```
[2017-04-23 10:59:42] Slack Websocket Try To Reconnect 0/360 - team-2
[2017-04-23 10:59:42] Slack Websocket is not open - team-2
Slack Authorization Finished - team-2
```
Attempt to send a message again in a channel on team-2
```
[2017-04-23 11:01:09] Slack Websocket Try To Reconnect 1/360 - team-2
[2017-04-23 11:01:09] Slack Websocket is not open - team-2
Slack Authorization Finished - former-residents

```

**Comment by benjamreynolds** [comment]
FWIW, I am using emacs-slack via the [slack layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bchat/slack) in [spacemacs](https://github.com/syl20bnr/spacemacs), This following is my system info from the spacemacs report issue command, if that is at all helpful. I am on the most recent `slack-20170422.956`

- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: br-slack-bindings (rev. 542a9d87)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv elixir javascript lua yaml html
     (ruby :variables ruby-version-manager 'rbenv ruby-test-runner 'rspec)
     ruby-on-rails helm auto-completion better-defaults emacs-lisp colors git github markdown org emoji
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     slack spell-checking syntax-checking scheme)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by benjamreynolds** [comment]
And now both of my slack teams are connecting just fine, with no discernible reason why it would work now when it wasnt earlier today. No configuration change, and no change to my internet connection.... 🤷‍♂️

**Comment by yuya373** [comment]
I think websocket is not connected while `slack-start`.
where is the error ` (unbound-slot slack-team "#<slack-team slack-team>" ims oref)` come from?
if websocket is successfully connected, `M-x list-processes`shows `wss://...`.

**Comment by benjamreynolds** [comment]
Im going to close this for now. Ive had a run of what I would see as "good luck" with my slack connection lately. I'll reopen with more detail if this crops up again.
