### ISSUE TITLE
alert is used instead of slack-custom-message-notifier on slack-message-delete--notify alert 

### ISSUE THREAD

**Issue by FrancisMurillo** [yuya373/emacs-slack#187]
Hello dood,

I was just wondering when a message is deleted in slack, an `alert` pops up. I traced it back to `slack-message-delete--notify` which seems to have a direct reference to it. I was surprised since I used the `slack-message-custom-notifier` to change the `alert` style to a `fringe` instead of a `popup`. Shouldn't the delete notifier use the user defined option instead?

By the way, the command for the unread rooms works nicely. #175

**Comment by yuya373** [comment]
Should use user defined notifer 😵

2017/05/11 22:25、Francis Murillo <notifications@github.com> のメッセージ:
