### ISSUE TITLE
Open Slack Buffer in the Current Buffer Window

### ISSUE THREAD

**Issue by stevenmccord** [yuya373/emacs-slack#202]
Was wondering if it was possible to open up a channel in the current window rather than it take the next available window?  Or is there a configuration option for that??  Thanks!

**Comment by FrancisMurillo** [comment]
Hello dood,

Have you tried `(setq slack-buffer-function #'switch-to-buffer)`?

**Comment by stevenmccord** [comment]
Worked perfectly, thanks @FrancisMurillo!
