### ISSUE TITLE
Feature request: function to close connections

### ISSUE THREAD

**Issue by OlafMerkert** [yuya373/emacs-slack#205]
I would like to have a function `slack-stop` which would close all connections (not necessarily chat buffers) and also not constantly try to reconnect.

Now, when I go offline, slack is spamming the minibuffer with messages about being unable to reconnect.

**Comment by yuya373** [comment]
`slack-ws-close` will do this.

**Comment by OlafMerkert** [comment]
Thanks, `slack-ws-close` did not work for me, I will investage further and try to reproduce the problem.

**Comment by OlafMerkert** [comment]
It seems I got into trouble because the slack channel buffers were still open, and something triggered them trying to reconnect.
