### ISSUE TITLE
Get to Pinned Items in a channel

### ISSUE THREAD

**Issue by stevenmccord** [yuya373/emacs-slack#207]
I see the function `slack-room-pins-list` and I call that within the open channel buffer, but nothing seems to happen.  I am probably doing something wrong, but wasn't sure if there was a way to get the items pinned in a particular channel.  Thanks!

**Comment by yuya373** [comment]
`slack-room-pins-list` is broken, #208 will fix.
thanks reporting.

**Comment by stevenmccord** [comment]
No worries, love the client.  I am on spacemacs, and just updated my packages, not sure if it would already be pushed out there though.  I saw the PR was merged in there.  But still not working for me.  Definitely could be on my side, just wanted to provide info here.  Thanks again!

**Comment by yuya373** [comment]
@stevenmccord 

still not working?

**Comment by stevenmccord** [comment]
@yuya373 yeah still not working for me.  I updated to the latest, and I am using spacemacs, not sure if that matters.  Let me know if you need more information.

**Comment by yuya373** [comment]
@stevenmccord 
Yes. `toggle-debug-on-error` then call `slack-room-pins-list`. let me know what you get.

**Comment by stevenmccord** [comment]
There is more information, but it has token info and stuff like that, so hopefully this is enough, but let me know.

```
Debugger entered--Lisp error: (cl-no-applicable-method slack-message-to-string nil 
```

**Comment by yuya373** [comment]
@stevenmccord 
thanks! Are there any than normal messages in pinned items? like file or file comment.

**Comment by stevenmccord** [comment]
@yuya373 the only thing pinned there is a slack post.

**Comment by yuya373** [comment]
@stevenmccord 
please eval below function, and tell me what `ITEMS` you get.

```
(defun slack-room-on-pins-list (items room team)
  (message "ITEMS: %s" items)
  (cl-labels ((buffer-name (room)
                           (concat "*Slack - Pinned Items*"
                                   " : "
                                   (slack-room-display-name room))))
    (let* ((messages (mapcar #'(lambda (m) (slack-message-create m team :room room))
                             (mapcar #'(lambda (i)
                                         (plist-get i :message))
                                     items)))
           (buf-header (propertize "Pinned Items"
                                   'face '(:underline
                                           t
                                           :weight bold))))
      (funcall slack-buffer-function
               (slack-buffer-create-info (buffer-name room)
                                         #'(lambda ()
                                             (insert buf-header)
                                             (insert "\n\n")
                                             (if (< 0 (length messages))
                                                 (mapc #'(lambda (m)
                                                           (insert (slack-message-to-string m team))
                                                           (insert "\n"))
                                                       messages)
                                               (insert "No Pinned Items"))))
               team))))
```

I got below on `*Messages*` buffer.

```
ITEMS: [(:type file :file (:id F8320AJD :created 1506430711 :timestamp 1506430711 :name ....]
```

I'm interested in `:type`.

**Comment by stevenmccord** [comment]
@yuya373 

here you go.

```
ITEMS: [(:type file :file (:id F6TSWGX6W :created 1503683491 :timestamp 1505756164 :name Belushi_Cloud_Development_Upgrade :title Belushi Cloud Development Upgrade :mimetype text/plain :filetype space :pretty_type Post 
```

**Comment by yuya373** [comment]
@stevenmccord #244 will fix this issue.
