### ISSUE TITLE
Cant register new team because no connection to localhost

### ISSUE THREAD

**Issue by klprint** [yuya373/emacs-slack#210]
I tried to register my team as described in the README but I don't manage to get it to work.

- I installed all dependencies
- I set up the API as described
- I run slack-register-team
- the browser opens, where I click "authenticate"
- the next page loads and says, that the server "localhost" is not available

What am I doing wrong? It seems as if the needed service is not started after authentication..

**Comment by mattpritchard4** [comment]
I have the same problem

**Comment by mattpritchard4** [comment]
The code appears in the address bar itself, i.e. "localhost:8080/?code=<copy this code>&state="

**Comment by klprint** [comment]
Ah, thank you very much, I did not understand that in the first place. Thanks again!

**Comment by mattpritchard4** [comment]
No problem, the install guide has some ambiguity in my opinion. When I have some time I am going to try to contribute to clear it up a bit.
