### ISSUE TITLE
Feature request: Add interactive function to copy message link

### ISSUE THREAD

**Issue by jtmoulia** [yuya373/emacs-slack#212]
This is to support [sharing links in slack](https://get.slack.help/hc/en-us/articles/204399343-Share-links-in-Slack).

The implementation I'm picturing: if the cursor is over a message and `slack-message-copy-link` is called, that message's link is copied to the clipboard.

**Comment by yuya373** [comment]
@jtmoulia 
![deepinscreenshot20170725173755](https://user-images.githubusercontent.com/3055271/28563163-068616c0-7160-11e7-90c2-b499432897be.png)

↑is this feature?

**Comment by jtmoulia** [comment]
Yes, that's exactly it.

**Comment by yuya373** [comment]
#215

**Comment by jtmoulia** [comment]
Thanks @yuya373(/moodymann) !
