### ISSUE TITLE
Feature Request: side bar listing channels/groups/im in one place

### ISSUE THREAD

**Issue by mattpritchard4** [yuya373/emacs-slack#219]
This package is working great and saving me from the memory hogs that are chrome and electron, but I was wondering if it would be possible to incorporate a function that opens a helm buffer or side bar that lists all open channels/im/groups in one place like the slack app itself (pictured below).  I currently have bindings to open a list for each of these individually, but it's a bit of a pain to navigate.

![slack-screenshot](https://user-images.githubusercontent.com/12675734/29217866-faf6e734-7e80-11e7-9b65-3a25de2a3305.jpg)

**Comment by dmusican** [comment]
@mattpritchard4 Can you clarify where this sidebar feature is? :) It would be nice to see a list of unread messages for all teams simultaneously.

**Comment by mattpritchard4** [comment]
I think the function I was referring to is "slack-select-unread-rooms". That should pull up a list of rooms/direct-messages/channels that have unread messages.

**Comment by matthew-piziak** [comment]
`slack-select-unread-rooms` doesn't work for direct messages (I just tested it). I filter `tracking-buffers` and use that.

**Comment by matthew-piziak** [comment]
Here's the code I use:
```
  (defun tracking-go-to-buffer (new)
    (interactive)
    (when (buffer-live-p (get-buffer new))
      (with-current-buffer new
        (run-hooks 'tracking-buffer-removed-hook)))
    (setq tracking-buffers (cdr tracking-buffers)
          tracking-mode-line-buffers (tracking-status))
    (if (buffer-live-p (get-buffer new))
        (switch-to-buffer new)
      (message "Buffer %s does not exist anymore" new)
      (ding)
      (setq tracking-mode-line-buffers (tracking-status)))
    (setq tracking-last-buffer (current-buffer))
    ;; Update mode line. See `force-mode-line-update' for the idea for
    ;; this code. Using `sit-for' can be quite inefficient for larger
    ;; buffers.
    (dolist (w (window-list))
      (with-current-buffer (window-buffer w))))

(defun counsel-tracking-buffers (&optional filter)
    (ivy-read "Tracking Buffers: " tracking-buffers
              :action 'tracking-go-to-buffer
              :predicate (lambda (tb) (s-match filter tb))))

(counsel-tracking-buffers "Slack")
```

**Comment by dmusican** [comment]
Got it -- thanks for the info.

**Comment by mattpritchard4** [comment]
@matthew-piziak That's odd, I'm able to see direct messages using `slack-select-unread-rooms`

**Comment by matthew-piziak** [comment]
Weird. I messaged myself so maybe the caching is weird. I may get someone to experiment with me.

**Comment by matthew-piziak** [comment]
That is, when I messaged myself it adding a tracking buffer but did not show up in `slack-select-unread-rooms`.

**Comment by mattpritchard4** [comment]
I haven't tried it by messaging myself, but DMs are coming through from my coworkers without any problem.
