### ISSUE TITLE
How to do slash commands?

### ISSUE THREAD

**Issue by FrancisMurillo** [yuya373/emacs-slack#222]
Hello dood,

For my team, I made a custom slash command to mark time in and out and can't seem to trigger it within the channel buffer. It does work when I go to the slack app but not withing the Emacs.

Is a special syntax in place? Or is it simply not allowed?

**Comment by yuya373** [comment]
@FrancisMurillo 

Slack seems using private api to handle slash command like `https://your-team-name.slack.com/api/chat.command?_x_id=56d71e21-1506397137.594`.
some slash commands are not supported until Slack make this api public.

currently these are implemented slash commands and executed by typing `/foo [bar]` in channel buffer.
https://github.com/yuya373/emacs-slack/blob/master/slack-slash-commands.el#L26

**Comment by FrancisMurillo** [comment]
Sadly, closing this issue then. Thanks for answering.
