### ISSUE TITLE
Broken formatting for ```fixed space blocks```

### ISSUE THREAD

**Issue by Malabarba** [yuya373/emacs-slack#228]
In slack messages, if you surround some text with 3 backtics on each side it indicates a pre-block where formatting and whitespace are preserved (a simple form of codeblocks).

However, in slack.el these blocks are filled as regular paragraphs which usually breaks formatting completely.  It would be nice if they could be detected and kept verbatim.

**Comment by yuya373** [comment]
@Malabarba 

How to reproduce?
I tried sending below message to @slackbot at slack web client and display the message at emacs-slack, it keeps spaces and blank lines correctly.

```

(declare-function zlib-decompress-region "decompress.c" (start end))

(defun url-handle-content-transfer-encoding ()
  (let ((encoding (mail-fetch-field "content-encoding")))
    (when (and encoding
	       (fboundp 'zlib-available-p)
	       (zlib-available-p)
	       (equal (downcase encoding) "gzip"))
      (save-restriction
	(widen)
	(goto-char (point-min))
	(when (search-forward "\n\n")
	  (zlib-decompress-region (point) (point-max)))))))
```

**Comment by Malabarba** [comment]
Odd. Maybe I have an advice or something messing that up. I'll look it up up today and either give you a reproducible example or close the issue.

**Comment by Malabarba** [comment]
Here's an example for me. In Emacs, I open a private chat with myself and send the same message you pasted above. The output I get on the chat buffer is below:

    (declare-function zlib-decompress-region "decompress.c" (start end))
    
    (defun url-handle-content-transfer-encoding ()
      (let ((encoding (mail-fetch-field "content-encoding"))) (when (and encoding
    	       (fboundp 'zlib-available-p)
    	       (zlib-available-p)
    	       (equal (downcase encoding) "gzip")) (save-restriction
    	(widen)
    	(goto-char (point-min))
    	(when (search-forward "\n\n")
    	  (zlib-decompress-region (point) (point-max)))))))

As you can see, some line-breaks were swallowed somehow. Also, the longer lines get wrapped on `lui-fill-column` (70 columns by default), which seems to be a feature of lui.

Don't you get this behaviour?

**Comment by Malabarba** [comment]
Hold on, I think I know what's causing the line-breaks getting swallowed. The line-wrapping is still annoying, but I suppose lui probably has a way of disabling that globally.

**Comment by Malabarba** [comment]
Actually, scratch that. I have no idea what's causing the swallowed lines.

**Comment by yuya373** [comment]
my `lui-fill-column` is 100.
```
lui-fill-column is a variable defined in ‘lui.el’.
Its value is 100
Original value was 70
```

after set `lui-fill-column` to 70, i got same output with yours.
```

(declare-function zlib-decompress-region "decompress.c" (start end))

(defun url-handle-content-transfer-encoding ()
  (let ((encoding (mail-fetch-field "content-encoding"))) (when (and
    encoding
	       (fboundp 'zlib-available-p)
	       (zlib-available-p)
	       (equal (downcase encoding) "gzip")) (save-restriction
	(widen)
	(goto-char (point-min))
	(when (search-forward "\n\n")
	  (zlib-decompress-region (point) (point-max)))))))
```

**Comment by Malabarba** [comment]
I guess it must be a lui bug then.

**Comment by unhammer** [comment]
I had it at 70 and it was still breaking markdown blocks. It seems like lui is doing just what it's expected to, calling fill-column on every message. It has no idea that some of the messages should not be broken. I worked around it with this:

```
  (defun my-slack-nobreak-mrkdwn ()
    "Return non-nil (don't break line) if point is in markdown code face."
    (seq-find (lambda (ov) (eq 'slack-mrkdwn-code-block-face (overlay-get ov 'face)))
              (overlays-at (point))))
  (add-hook 'slack-message-buffer-mode-hook
            (lambda ()
              (add-hook 'fill-nobreak-predicate #'my-slack-nobreak-mrkdwn nil 'local)))
```
