### ISSUE TITLE
Image displays incorrectly (slack-mapconcat-images issue)

### ISSUE THREAD

**Issue by accidentalrebel** [yuya373/emacs-slack#229]
Whenever I open an image from the slack buffer the image that gets displayed looks like this:

![upside_down](https://user-images.githubusercontent.com/1009214/30626206-e6329566-9dfa-11e7-94e4-ce71097eeb14.PNG)

I looked at the code and found out that it has something to do by the sorting of images based on the emacs version. This can be found under `slack-mapconcat-images` function in `slack-util.el`:

```emacs-lisp
(let ((compare (if (< emacs-major-version 26)
                                                #'>
                                              #'<))
...
```
I'm using 25.3 so changing the code to check for emacs-major-version 25 fixed the issue.
```emacs-lisp
(let ((compare (if (< emacs-major-version 25)
                                                #'>
                                              #'<))
...
```

![upside_up](https://user-images.githubusercontent.com/1009214/30626202-dfedd6de-9dfa-11e7-8597-1483d01db77a.PNG)

I could submit a fix for this but unsure up to what version this bug is happening. I tested the bug on 25.2 and 25.3 and the changes above fixed the issue for both versions.

Anyone know if this happens 25.1 below? Or better yet, if anyone can teach me how to test up test environments so I could test on multiple versions of Emacs easily?

Thanks a lot!

**Comment by yuya373** [comment]
@accidentalrebel 

I confirmed same issue in 25.3 (↓).  and your patch fixes it.

```
This is GNU Emacs 25.3.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19)
 of 2017-09-25
```
I will check Emacs 25.3 on OSX later.

**Comment by accidentalrebel** [comment]
Glad to hear that it works. :)

**Comment by yuya373** [comment]
@accidentalrebel 

I tried Emacs 25.3 on OSX, images rendered correctly without your patch.

```
This is GNU Emacs 25.3.50.3 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1611))
 of 2017-09-25
```
it seems this is specific to below Emacs 25 and OSX.

**Comment by accidentalrebel** [comment]
I see. So it seems that the patch should only be applied to Windows and Linux, then have things unchanged for OSX.

Should I go ahead and send a pull request?

**Comment by yuya373** [comment]
@accidentalrebel 
Yes, please.
