### ISSUE TITLE
White space around messages

### ISSUE THREAD

**Issue by mattford63** [yuya373/emacs-slack#23]
This is awesome good work.

I see a lot of white space around every message in a buffer - is that expected? Around 3 blanks lines after a post.

**Comment by yuya373** [comment]
when i turn on whitespace-mode in slack message buffer, looks like this.
<img width="940" alt="2015-12-23 14 20 45" src="https://cloud.githubusercontent.com/assets/3055271/11971401/9620899a-a980-11e5-80b0-64f11c483264.png">

I can't see white space around messages, but there is on the prompt line.

Can you show me screenshot?

**Comment by ryuslash** [comment]
But there are 3 or more blank lines after each message. One of them looks like a placeholder for reactions?

**Comment by mattford63** [comment]
Your screenshot is as mine.  Is it possible to make the blank lines go away?

**Comment by yuya373** [comment]
I totally gotit, It can be reduced.
Is this ok?

![2015-12-24 10 14 19](https://cloud.githubusercontent.com/assets/3055271/11987710/a0cd6398-aa27-11e5-8190-1785ed5fee67.png)
my message itself sometimes contain blank line, but slackbot's message is exactly one line.
