### ISSUE TITLE
[Question] Message time only has time, not date

### ISSUE THREAD

**Issue by jasoncyu** [yuya373/emacs-slack#233]
When I view messages, I see the timestamp like this: 

![image](https://user-images.githubusercontent.com/1874847/30839243-7f0602c2-a225-11e7-9e12-a0befa03ff38.png)

It has [HH:MM] but in the screenshots of this repo, I see both date and time. Can someone point me to the code that controls this so I can further debug?

**Comment by yuya373** [comment]
this is my timestamp settings.

```
  (setq lui-time-stamp-format "[%Y-%m-%d %H:%M:%S]")
  (setq lui-time-stamp-only-when-changed-p t)
  (setq lui-time-stamp-position 'right)
```

**Comment by jasoncyu** [comment]
Nice, that works for me, thanks!
