### ISSUE TITLE
websocket error on start

### ISSUE THREAD

**Issue by gdanov** [yuya373/emacs-slack#239]
I'm getting
```Error (websocket): in callback `on-message': File error: "Creating pipe", "Too many open files"```
repeated 47 times during slack start-up.
I don't know if that's connected, but some channels' unread items never get synced

**Comment by revmischa** [comment]
I get this too. I tried upping my open file limit but without much luck:

```
$ launchctl limit maxfiles
	maxfiles    64000          524288         
```

<img width="833" alt="screen shot 2018-01-28 at 00 15 57" src="https://user-images.githubusercontent.com/245131/35473838-8b981ff0-03c0-11e8-878d-f0455c78d391.png">

**Comment by nicklan** [comment]
What was the reason for closing this? I'm still getting this. I think it's during emoji download, so not a major issue, but would be good to fix:
```
[2020-11-16 10:48:08] [error] [snip] Error on ‘websocket-open’. TYPE: on-message, ERR: (file-error Creating pipe Too many open files)
Download Failed. STATUS: exit, EVENT: exited abnormally with code 125
, URL: https://emoji.slack-edge.com/T02EPKPG3/sidisupset/e7b408fae42bb3b6.png, NAME: /tmp/.slack-images/c244fd994918d6fb76ea23eb76314923.png, OUTPUT: 
```
