### ISSUE TITLE
Add support for reading-writing snippets

### ISSUE THREAD

**Issue by DamienCassou** [yuya373/emacs-slack#242]
When someone sends a snippet, I get a link to a webpage. I would prefer that the snippet is inlined. Bonus point with syntax highlighting.

When sending a snippet, I would like to send the current region (in a prog-mode buffer for example) and get a list of rooms to post to.

Is there any planned support for that?

**Comment by DamienCassou** [comment]
I wrote this as an experiment for sending snippets. I copy/pasted `slack-file-upload`:

```emacs
(defun slack-file-send-region-snippet ()
  (interactive)
  (cl-labels
      ((on-file-upload (&key data &allow-other-keys)
                       (slack-request-handle-error
                        (data "slack-file-upload")))
       (select-channels (channels acc)
                        (let ((selected (apply slack-completing-read-function
                                               (if acc
                                                   (list "Select another channel (or leave empty): "
                                                         (cons "" channels) nil t)
                                                 (list "Select channel: " channels nil t)))))
                          (if (< 0 (length selected))
                              (select-channels (remove-if (lambda (x) (equal selected (car-safe x))) channels)
                                               (cons selected acc))
                            acc)))
       (channel-id (selected channels)
                   (oref (cdr (cl-assoc selected channels :test #'string=))
                         id)))
    (let* ((team (slack-team-select))
           (channels (slack-room-names
                      (append (oref team ims)
                              (oref team channels)
                              (oref team groups))))
           (target-channels (select-channels channels '()))
           (channel-ids (mapconcat #'(lambda (selected)
                                       (channel-id selected channels))
                                   (cl-delete-if #'null target-channels)
                                   ","))
           (filetype "javascript")
           (initial-comment (read-from-minibuffer "Message: ")))
      (slack-request
       (slack-request-create
        slack-file-upload-url
        team
        :type "POST"
        :params (list (cons "filename" "fichier.js")
                      (cons "channels" channel-ids)
                      (cons "filetype" filetype)
                      (cons "mode" "snippet")
                      (if initial-comment
                          (cons "initial_comment" initial-comment)))
        :files (list (cons "file" (with-current-buffer (generate-new-buffer " slack-snippet")
                                    (insert "function test(a) {	return a + 1; }")
                                    (current-buffer))))
        :headers (list (cons "Content-Type" "multipart/form-data"))
        :success #'on-file-upload)))))
```

**Comment by DamienCassou** [comment]
If anyone is interested, I can turn that into a PR (removing duplication with `slack-file-upload`).

**Comment by jtmoulia** [comment]
I'm not a maintainer, but inlining the snippets would be especially useful for me.

Additionally, I'll bet I'd use slack snippets more if I had that `slack-file-send-region-snippet` function to take advantage of.

Happy to test if/when a PR is available.

**Comment by PrismaPhonic** [comment]
@yuya373  why was this closed as completed? I don't see a command to insert the current region as a snippet. I also don't get inline previews of snippets with syntax highlighting - they show up as attachments for me

**Comment by ag91** [comment]
@PrismaPhonic for awareness yuya373 decided to invest his time is other nice projects (hope he is doing cool stuff because emacs-slack is surely cool)
I am maintaining the package, let me have a look :)

**Comment by ag91** [comment]
so this was likely closed because there is a `slack-file-upload-snippet` function now. So the writing part is done.
You have a point that the reading is not yet there. Added a commit that addresses that (at least partially: this shows just a preview, for some reason -probably length- the full content of the snippet doesn't come: so you will have to open in browser)

**Comment by PrismaPhonic** [comment]
@ag91 if you have any ideas: https://github.com/emacs-slack/emacs-slack/pull/623
