### ISSUE TITLE
Unable to open channels which contain an "uploaded email"

### ISSUE THREAD

**Issue by jtmoulia** [yuya373/emacs-slack#249]
When trying to open a channel which contains an [uploaded email](https://get.slack.help/hc/en-us/articles/206819278-Send-emails-to-Slack), I get the log below in `Slack Log` / `Messages`, but the channel buffer never opens:

```
[2017-10-16 12:10:29] Slack Authorization Finished - HealthTensor
[2017-10-16 12:10:29] Slack Websocket Is Ready! - HealthTensor
[2017-10-16 12:10:32] There is no message in slackbot. fetching from server... - HealthTensor
```

Symptom-wise, this issue is similar to #248 

Let me know however I can help debug: I love this package, but haven't been able to use it.

**Comment by agzam** [comment]
Yeah, this bug unfortunately preventing me from using this package as well. I love it though. I hope this gets fixed soon.

**Comment by jcpetkovich** [comment]
I'm also running into this issue.

**Comment by stubillwhite** [comment]
I'm hitting this issue too, when the channel contains a shell text snippet. It's quite easy for me to reproduce:

1) Start a private chat with Slackbot in the browser and in Emacs
2) Enter a text snippet in the browser; Emacs displays the text snippet correctly
3) Run slack-start in Emacs to restart Slack
4) Attempt to connect to the chat with Slackbot again and you receive the error above

Deleting the snippet from the channel results in Emacs being able to connect again.

I'm struggling to debug this, but if there are things I can try then do let me know.

**Comment by stubillwhite** [comment]
I haven't had time to debug this, but if it's preventing you from using the plugin then I'm currently using this workaround:

        (defun sbw/slack-mode--catch-message-to-string-error (orig-fun &rest args)
          (condition-case nil
              (apply orig-fun args)
            (error "<error parsing message>\n")))
        (advice-add 'slack-message-to-string :around #'sbw/slack-mode--catch-message-to-string-error)

It just catches the error and replaces the offending message with some placeholder text. Just a sticking plaster, but it means I can still use slack-mode for now until I get time to look into the issue in more detail.

**Comment by NicholasTD07** [comment]
@stubillwhite Thanks for the workaround!

**Comment by creichert** [comment]
The fix did work for me. Unfortunately, it's also catching uploaded files so I can't see images. I'm not sure how to proceed but looking into it if anyone has any other ideas.

**Comment by yuya373** [comment]
I receive a lot of emails from Github in slack, but I have not encounter this issue.
stack trace is helpful (mask private infomation)
