### ISSUE TITLE
Error (websocket): in callback `on-message': Symbol's value as variable is void: file

### ISSUE THREAD

**Issue by alan-ghelardi** [yuya373/emacs-slack#250]
I'm running Emacs 25.3.1, slack-20171011.1945 and websocket-20170829.457. The following warning appears very often altough I haven't realized yet any trouble with the behavior of Emacs Slack (I installed it today after setting up a new development machine - It's been around six months that I use the package):
`Error (websocket): in callback `on-message': Symbol's value as variable is void: file`
Any idea about the reason or how can I help in finding out the isssue?

**Comment by alan-ghelardi** [comment]
I've found another regression on the version mentioned above. When I try the command `slack-message-add-reaction` the folowing error is raised:
`Invalid function: (file-comment-id (slack-get-file-comment-id))`

**Comment by yuya373** [comment]
@alan-ghelardi 

please eval below snipped, then try `slack-message-add-reaction` .

```
(when (not (fboundp 'if-let*))
  (defalias 'if-let* #'if-let))
```

**Comment by alan-ghelardi** [comment]
Thanks for the prompt answer.

The expression has returned t and `slack-message-add-reaction` has 
produced the same error. Just for clarifying (not sure if this was clear 
in the previous message), the error happens when I try to select an hemoji.

**Comment by NicholasTD07** [comment]
I am getting the same error too and some others:

```
Error (websocket): in callback `on-message': Invalid function: (initial-comment (plist-get file :initial_comment))
Error (websocket): in callback `on-message': Invalid function: (initial-comment (plist-get file :initial_comment))
Error (websocket): in callback `on-message': Symbol's value as variable is void: file
Error (websocket): in callback `on-message': Symbol's value as variable is void: file
```

Emacs: 25.3.1
websocket: 20171113.2045 
slack: 20171123.721

**Comment by alan-ghelardi** [comment]
I've realized that some of those errors appear when the channel contains 
an uploaded file. In my case this is making the package unusable. So I 
reverted the package to the commit e7fed85 which seems more stable.

**Comment by NicholasTD07** [comment]
Got this error message when I try to add reaction to a message. `slack-message-add-reaction: Invalid function: (file-comment-id (slack-get-file-comment-id))`

**Comment by NicholasTD07** [comment]
@alan-ghelardi If you want to use the latest package, you might want to try out this workaround. It might help depends on what error you were running to. It helped me.
