### ISSUE TITLE
Unread room list and last message in room unreliable

### ISSUE THREAD

**Issue by gdanov** [yuya373/emacs-slack#253]
I seem to have problem with rooms that contain attached files. The client throws an error when it reaches the file message and the rooms load only to that point. See the error trace bellow

**Comment by gdanov** [comment]
hope this error trace helps
![...](https://lh3.googleusercontent.com/nhbNJUIgtOhwcBMxwE9tqDaLuHHj-ckSI6MfnV55T_AKY8r75_6V0txBBH3pUmSUMZn139GK4X_cicaiQVFQ_IfqnESDlOXPNyaTI38pTHu6nVv5dMol1C4Oy-iOugme9A5xE-iYGQ=w3354-h618-no)

**Comment by gdanov** [comment]
I patched the method to just catch the exception and report it in the *messages* buffer. After I managed to load once the problematic channels (seeing the error reported), the next time I open these channels everything is smooth. The problem seems to be related to the initial sync of channels with attached files only.

**Comment by taohansen** [comment]
how did you do this?

**Comment by taohansen** [comment]
my message history is also unreliable. what’s worse, messages i enter appear twice, one after the other in the buffer as if accidentally sent doubly. yet entering the Slack browser app shows the message as sent only once.

**Comment by gdanov** [comment]
I patched slack-message-to-string method in the slack-file-share-message.el file to catch the exception. Something like this
```(defmethod slack-message-to-string ((m slack-file-share-message) team)
  (cl-labels
      ((redisplay () (slack-message-redisplay m (slack-room-find (oref m channel) team))))
    (condition-case ex				
........
	('error (message (format "Caught exception: [%s] %s" ex m)))```

**Comment by agzam** [comment]
I confirm, messages are missing. ;(

**Comment by Soren-Nordstrom** [comment]
I can confirm this also.  Messages load from a couple of weeks ago, but nothing more recent.  Emacs 25.3.1 Slack 20171017.822
