### ISSUE TITLE
Error when joining some channels

### ISSUE THREAD

**Issue by jmayfield74** [yuya373/emacs-slack#254]
Channels that I am subscibed to and have been using for a while now have recently stopped working. When I try to join the channel initially, nothing happens and no errors mesages appear. When I look at the buffer list I see the buffer for the room I tried to join, but when I select it, it's contents are quite old. If I try again to join the same room, i get this message/error:

`Invalid function: (initial-comment (oref (oref m file) initial-comment))`

Strangely, some channels work fine

**Comment by jtmoulia** [comment]
These are the exact same symptoms I'm seeing with #249 (having an uploaded email, or some other unsupported slack message, causes the channel to not open and the unread count to go stale)
