### ISSUE TITLE
Got "Invalid function" error while trying to get message

### ISSUE THREAD

**Issue by everiori** [yuya373/emacs-slack#255]
While using slack-im-select function, I got below error:
Invalid function: (initial-comment (oref (oref m file) initial-comment))

And idea how to fix it? Thanks.

**Comment by thiderman** [comment]
I have seen this as well!

Perhaps in a related vein, whenever someone makes a reaction to a message, I see
```
Error (websocket): in callback `on-message': Invalid function: (old-reaction (slack-reaction-find m reaction))```

Could the two be related or should I make a separate issue?

**Comment by thiderman** [comment]
Also, related to #254

**Comment by yuya373** [comment]
which version of Emacs do you use?

**Comment by yuya373** [comment]
I think this is because `if-let*` is undefined in old version, https://github.com/yuya373/emacs-slack/commit/c8f4c3312b574b8f4cd5ddaaa6ec7710893a9ff0 seems not working correctly.

**Comment by thiderman** [comment]
I'm on `GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19) of 2017-09-16`, Arch Linux. I do have an `if-let*` (and `-if-let*` and others), so I'm not sure that's the problem.

**Comment by everiori** [comment]
My Emacs version is GNU Emacs 25.3.2,  is it related? How to confirm that if-let* is defined?

**Comment by jcpetkovich** [comment]
I can confirm that having `if-let*` does not solve the problem.

**Comment by jcpetkovich** [comment]
Interestingly when I delete all the compiled elisp files in  `~/.emacs.d/elpa/slack-*/` the issue dissapears. This issue must be related to macro-expansion.

**Comment by everiori** [comment]
Remove elpa/slack-* works for me, too. Close this issue.
