### ISSUE TITLE
Unable to run slack-channel-select: invalid function

### ISSUE THREAD

**Issue by christoofar** [yuya373/emacs-slack#266]
When calling M-x slack-channel-select (using MELPA version 20171202.1233) I get this error in the minibuf:

`Invalid function: (buf (cl-find-if (function (lambda (buf) (string= (buffer-name buf) (slack-buffer-name class room team)))) (slot-value \
team class)))`

I pulled the [last commit](https://github.com/christoofar/emacs-slack/commit/bbcf1047e2e9aabfdcee6cc152557755f35190b8) instead and it appears this goes away.  Just want to let anyone know in case the see an issue with the last MELPA package.

It's happening to me on OSX, GNU/Linux and also on MSYS2/Win versions of emacs 26 and 27.

**Comment by shackra** [comment]
I'm experiencing the same with `slack-select-rooms`:

```
(buf (cl-find-if (function (lambda (buf) (string= (buffer-name buf) (slack-buffer-name class room team)))) (slot-value team class)))
```

**Comment by ripple0328** [comment]
I got the same issue

**Comment by jgoerzen** [comment]
Also have this with the IM functions

**Comment by nickanderson** [comment]
slack-20171217.2027 I am seeing the same with slack-select-channel

```
Invalid function: (buf (cl-find-if (function (lambda (buf) (string= (buffer-name buf) (slack-buffer-name class room team)))) (slot-value team class)))
```

**Comment by nickanderson** [comment]
I rebuilt all of my elpa packages and the error disappeared.

**Comment by christoofar** [comment]
Error is gone for me after an update from MELPA.  Closing this issue.

**Comment by jgoerzen** [comment]
Now with slack-im-select, I get "Symbol's value as variable is void: user"

**Comment by luka-n** [comment]
+1 @jgoerzen

**Comment by luka-n** [comment]
I get the same as jgoerzen

**Comment by christoofar** [comment]
I would recommend creating a new issue as the nature of the error might be completely different.

**Comment by rekado** [comment]
FWIW I still have this issue when building from source.  I packaged this and its dependencies for GNU Guix which extracts autoloads and bytecompiles the source files.

In order to make it work I have to manually M-x eval-buffer on some of the source files.
