### ISSUE TITLE
Can I use emacs-slack with a proxy?

### ISSUE THREAD

**Issue by wxjeacen** [yuya373/emacs-slack#270]
As the title.
I would like to use proxy behind emacs-slack. Is there any way I can do that?

**Comment by catern** [comment]
The primary issue with this is that emacs-websocket doesn't support HTTP proxies at the moment. https://github.com/ahyatt/emacs-websocket/issues/73 But I've got some hacky modifications to websocket.el to add proxy support, which are sufficient to get emacs-slack working.
