### ISSUE TITLE
Error on slack-im-select: "Symbol's value as variable is void: user"

### ISSUE THREAD

**Issue by luka-n** [yuya373/emacs-slack#271]
I have latest version of emacs-slack, running emacs-snapshot on Debian, version 27.0.50 it says.

**Comment by bschlemmer** [comment]
Can't add anything useful to the debugging here but merely confirm that I'm experiencing the same issue.

**Comment by bschlemmer** [comment]
A little more information, from trial and error things start to go wrong at this commit id:

3439cc7c87000c9fea5655cba877100c2a857c02

prior to that slack-im-select works okay. 

PS. I did try directly from master as well in case MELPA was behind.

**Comment by revmischa** [comment]
Getting this too
