### ISSUE TITLE
Invalid Function in slack-user-name

### ISSUE THREAD

**Issue by michaeldjeffrey** [yuya373/emacs-slack#275]
when I `M-x slack-im-select` or pretty much anything, I get the message `slack-user-name: Invalid function: (user (slack-user--find id team))`.

If I grab the `id` and the `team` I can call `slack-user--find` by itself and it works. But never from another another function.

Version: 20180103.1928

**Comment by declanqian** [comment]
I came across this problem lately too.

**Comment by declanqian** [comment]
It's has been fixed on the master branch. Just tried.

**Comment by zvbuhl** [comment]
Try my fix from #277
