### ISSUE TITLE
Slack channels are no longer being listed 

### ISSUE THREAD

**Issue by alan-ghelardi** [yuya373/emacs-slack#276]
As of now (2018-01-15), the package suddenly stopped of displaying the channels that I've subscribed when I enter the command `slack-channel-select`. Not sure if there is some breaking change in the Slack Web API, but until the last Friday (when we used the package for the last time) everything was working fine and I didn't change anything. I continue to see messages that are being sent in my subscribed channels by looking at the Message buffer, but I can't access those channels.  

Is there a different way of opening a Slack channel? I am not able to do anything relevant without using the command slack-channel-select.

**Comment by masfj** [comment]
me too.

It is probably a bug in the Slack.

**Comment by alan-ghelardi** [comment]
@masfj Thank you very much for your answer. I fixed the issue locally by modifying the file slack-channel.el according to your comment:
```(defconst slack-channel-list-url "https://slack.com/api/channels.list?exclude_members=true")```

**Comment by alan-ghelardi** [comment]
As per the Slack's documentation: https://api.slack.com/methods/channels.list, perhaps the exclude_member parameter should be passed by default to avoid problems with large teams.
