### ISSUE TITLE
Nothing happens upon confirming selection in slack-im-select

### ISSUE THREAD

**Issue by rekado** [yuya373/emacs-slack#277]
I successfully set up a token and I can list channels, but when I select slackbot in `slack-im-select` nothing seems to happen.  After setting `url-debug` to `t` I see in the `*URL-DEBUG*` buffer that a request is made, but nothing ever seems to be received.

When I visit the URL in a browser I get a JSON response.

**Comment by piotr-yuxuan** [comment]
Just out of curiosity, what version of emacs do you use? and have you tried using the latest `HEAD` of emacs-slack?

**Comment by masfj** [comment]
I have experienced this, but at that time it was due to timeout.
Please check the *Messages* buffer.

I am setting as follows:
(custom-set-variables '(slack-request-timeout 60)) ; default value is 10.

**Comment by rekado** [comment]
This didn't help.  The message buffer doesn't tell me much:

```
Contacting host: slack.com:443
[2018-01-23 13:11:17] Slack Authorization Finished - emacs-slack
Contacting host: slack.com:443 [5 times]
[2018-01-23 13:11:22] Slack Channel List Updated - the-name|of-the-group
[2018-01-23 13:11:27] Slack Group List Updated - the-name|of-the-group
Contacting host: slack.com:443
[2018-01-23 13:11:28] Slack Im List Updated - the-name|of-the-group
slack-user-name: Invalid function: (user (slack-user--find id team))
```

At this point I forgot to `M-x eval-buffer` in `slack-user.el`, so I do that and run `M-x slack-im-select`.

````
No Message in slackbot, fetching from server...
Contacting host: slack.com:443
```

That's all there is.

**Comment by zvbuhl** [comment]
What worked for me on emacs 26.0.91 was globally replacing `slack-if-let*` with `if-let*`.
