### ISSUE TITLE
Cannot connect / too many open files + constant reconnections

### ISSUE THREAD

**Issue by tinder-jonathanwilner** [yuya373/emacs-slack#289]
Hi all,

First off, thanks for a great tool from Emacs that has worked well for sometime. Unfortunately, at least for me, things are pretty broken when trying to use the tool against either of two company slack instances. I'm getting enormous (6M) backtraces, long delays + then constant TLS retries attempting to talk to the auth servers for each message. I've attempted to both shorten and lengthen the server timeout with no success. 

It's actually challenging for me to debug - the backtrace is so huge, I can't figure out what's going on - and I can't really navigate through the trace, which is a huge dump of lisp with Slack variables/IDs mixed in.

Is the app working for anyone else - and do you have tips?

I am trying both from HEAD and from Melpa.

**Comment by howdoicomputer** [comment]
I haven't been able to get it to work.

I can authenticate but I  get `[2018-03-08 11:02:52] Retrying Request After: 1 second, URL: https://slack.com/api/channels.info, PARAMS: ((channel . C1U2BBJES))` over and over whenever I try to do anything.
