### ISSUE TITLE
Symbol's value as variable is void: slack-team-kill-buffers

### ISSUE THREAD

**Issue by chaseleinart** [yuya373/emacs-slack#291]
Hello - I just installed the slack package version 20180209.1923 from MELPA. I'm using GNU Emacs  24.5.1 on Ubuntu 16.04, and when calling slack-register-team, I'm receiving an error "Symbol's value as variable is void: slack-team-kill-buffers". I've gone through the process of creating a slack app, and obtaining the client id and secret, but calling this function returns this error before ever prompting me for the credentials. Please let me know if there are any further details I can provide to help.

Thanks,
Chase.

**Comment by yuya373** [comment]
@chaseleinart 
`slack-team-kill-buffers ` using `cl-defmethod` in `cl-generic`package to define function. (Emacs 26)

in https://elpa.gnu.org/packages/cl-generic.html

>  This is a forward compatibility package, which provides (a subset of) the
features of the cl-generic package introduced in Emacs-25, for use on
previous emacsen.

so, `(require 'cl-generic)` before `(require 'slack)` may resolve this issue.

**Comment by ipmsteven** [comment]
Hi @chaseleinart , I have the same issue and upgrade emacs to 26 would resolve it :)
