### ISSUE TITLE
provide tab completion for nicks

### ISSUE THREAD

**Issue by hexmode** [yuya373/emacs-slack#296]
As per title.  @mentions don't seem to be working, so that would need solving as well.

**Comment by kidd** [comment]
Artur Malabarba has a solution in his [blogpost](http://endlessparentheses.com/keep-your-slack-distractions-under-control-with-emacs.html) 
```lisp
;;; Bring up the mentions menu with `@', and insert a
;;; space afterwards.
(define-key slack-mode-map "@"
  (defun endless/slack-message-embed-mention ()
    (interactive)
    (call-interactively #'slack-message-embed-mention)
    (insert " ")))
```
