### ISSUE TITLE
Invalid HTTP header sent

### ISSUE THREAD

**Issue by Jumblemuddle** [yuya373/emacs-slack#300]
I keep getting a `Invalid HTTP header sent` error. I've tried with `:client-id` and `:client-secret` then getting the code out of the url from the redirect to `localhost:8080`. (Should this not 404?)
I've also tried with all three, including a valid `:token` from my browser—still no luck.
Perhaps `:name` shouldn't just be the name of the team?
Any help would be appreciated.

**Comment by nshi** [comment]
I'm getting the same error during initial connect. Any help on this would be appreciated.
```
error in process filter: websocket-outer-filter: Invalid HTTP header sent
error in process filter: Invalid HTTP header sent
```

**Comment by jasonmj** [comment]
Unfortunately the issue persists after updating both emacs-websocket and emacs-slack.

**Comment by yuya373** [comment]
I confirm if emacs version is 25 or below or gnutls is not available, this error happens. 
 Workaround is pass `:websocket-nowait nil` to `slack-register-team`.

**Comment by jasonmj** [comment]
Adding `:websocket-nowait nil` to `slack-register-team` worked. Thank you!
