### ISSUE TITLE
How do you login to an account that uses 2FA?

### ISSUE THREAD

**Issue by themattchan** [yuya373/emacs-slack#305]

**Comment by piotr-yuxuan** [comment]
Yeah, it's an hindrance :-( would you like to state if it's even currently possible? or what are the problems that must be fixed for that to work?

**Comment by damien-biasotto** [comment]
Not sure about slack, but usually a service using 2FA, will allow you to create a app secret token, that will act like a password.

**Comment by picaschaf** [comment]
Why was this issue closed? Should it be supported now? Since we enabled 2FA no login is possible.
