### ISSUE TITLE
No method definition: slack-message-append-reaction

### ISSUE THREAD

**Issue by vickenty** [yuya373/emacs-slack#34]
Occasionally a `*Warnings*` buffer pop up with the following message:
```
Error (websocket): in callback `on-message': No method definition: slack-message-append-reaction, (nil [object slack-reaction "slack-reaction" [...]
```

I see that the method is actually defined in slack-message-reaction.el, and tried re-loading the file without much success. Version used is 20160110.1829 from melpa.

**Comment by yuya373** [comment]
Is your Emacs version under 25?
I reproduced same error, but error message is different slightly.
I got `No applicable method: slack-message-append-reaction, nil, [eieio-class-tag--slack-reaction "grinning"....`
I use Emacs version 25.0.50.1, and eieio looks made some changes to error message.

**Comment by vickenty** [comment]
My Emacs' version is 24.5.1

**Comment by yuya373** [comment]
I think this fixed in latest version.
