### ISSUE TITLE
Starting an IM with multiple users

### ISSUE THREAD

**Issue by matthew-piziak** [yuya373/emacs-slack#340]
Is this possible to do from `emacs-slack`? I can interact with conversations once they're started but I can only seem to manage to start an IM with one person from within Emacs.

**Comment by yuya373** [comment]
`slack-group-mpim-open` creates multiparty direct message.

**Comment by matthew-piziak** [comment]
Thank you!!

**Comment by matthew-piziak** [comment]
Hmmm. Actually, when I call `slack-group-mpim-open`, it doesn't stop querying me for more users. How do I terminate the command so that it creates a room with the users that I've selected so far?

**Comment by yuya373** [comment]
`slack-group-mpim-open` has save behavior with #152 .
if you using helm, this may be help.
https://github.com/yuya373/emacs-slack/issues/152#issuecomment-278335573

**Comment by yuya373** [comment]
https://github.com/yuya373/emacs-slack/pull/173

↑is not implemented for `slack-group-mpim-open`,  can't quit loop with some `completing-read` replacements .

**Comment by matthew-piziak** [comment]
Great! `C-M-j` (input current without completion, effectively the same as empty string) works for `counsel`. Thank you!

**Comment by matthew-piziak** [comment]
I agree with https://github.com/yuya373/emacs-slack/issues/152#issuecomment-281474300 that this just needs a touch better messaging. The behavior itself is great.

**Comment by yuya373** [comment]
like https://github.com/yuya373/emacs-slack/pull/173/files ,  appending `(or leave empty)` is enough?

**Comment by matthew-piziak** [comment]
Yes, I think that should be enough. Then it is the responsibility of the user to send an empty string with whatever their completion framework is.
