### ISSUE TITLE
Images not always displayed in Slack buffer

### ISSUE THREAD

**Issue by matthew-piziak** [yuya373/emacs-slack#342]
I notice that sometimes, but not always, images are not displayed in the slack buffer. I see the username header and that's it. Is this a known issue?

**Comment by yuya373** [comment]
Are there any messages like [this](
https://github.com/yuya373/emacs-slack/blob/master/slack-util.el#L454) or [this](
https://github.com/yuya373/emacs-slack/blob/master/slack-util.el#L351) in Messages buffer?

**Comment by matthew-piziak** [comment]
Nope. I don't see anything like "Download Failed" or "Error Fetching Image", but I will keep an eye out for it.

**Comment by matthew-piziak** [comment]
Yeah, I just replicated it. Nothing at all in the Messages buffer. Sorry for the vague report.

**Comment by yuya373** [comment]
buffer's major mode is `slack-message-buffer-mode`?

**Comment by matthew-piziak** [comment]
That's right.

**Comment by yuya373** [comment]
I think images may be incompletely stored.  
If you clear the image cache, an error message is displayed or the image is displayed normally.

## clear image cache
- clear all images in `slack-image-file-directory`.
or
- find image file path by execute `describe-text-property` and press <kbd>RET</kbd> on `[Show]` of display property
  - then remove the image.

## re-download image
- `kill-buffer`  
- open the buffer

**Comment by matthew-piziak** [comment]
I killed all the images in `slack-image-file-directory` (in my case this was `/tmp/`), and reloaded the buffer. No dice.

I was not able to find the precise image file path with `describe-text-property`. Can you tell me more specifically where my cursor should be?

**Comment by yuya373** [comment]
:cry: 

I found better way to debug.

- eval below method
```
(defmethod slack-message--inspect ((this slack-message) room team)
  (format "TEAM: %s\nROOM: %s\nTS: %s\nMESSAGE: %s\nATTACHMENT-IMAGES: %s\nFILES: %s"
          (oref team id)
          (oref room id)
          (slack-ts this)
          (eieio-object-class this)
          (mapcar (lambda (e) (slack-image-spec e))
                  (oref this attachments))
          (mapcar (lambda (e) (slack-file-image-spec e))
                  (oref this files))))
```

- execute `slack-message--inspect` on the message's username header
- `slack-message--inspect` will output some  image urls, open these urls in browser to ensure images exists.
  - or execute `(slack-url-copy-file url "somedirectory/foo.png" :token "your slack token")`, check "somedirectory/foo.png".
- `slack-message--inspect` output `TEAM`, `ROOM`,  `TS` in Messages buffer, fill in below `let` bindings with these values. and execute below script.

```
(let* ((team-id "")
       (room-id "")
       (ts "")
       (team (slack-team-find team-id))
       (room (slack-room-find room-id team))
       (message (slack-room-find-message room ts)))
  (message "--------BEGIN-------")
  (message "%S" (slack-message-to-string message team))
  (message "--------END-------")
  "")
```
- if message contains image,  output like `(image :type imagemagick :file "/tmp...." :scale 1.0011363636363637 :height 360 :width 312)` will appear

I think images are broken or message does not contain image.

**Comment by matthew-piziak** [comment]
I'll go ahead and close this ^_^;;

Thanks again!
