### ISSUE TITLE
Tracking buffers reset when internet connection changes

### ISSUE THREAD

**Issue by matthew-piziak** [yuya373/emacs-slack#348]
I notice that when I move my laptop from ethernet to WiFi, all my channels get listed in the tracking buffers. This might be tricky to fix but I thought I'd mention it.

**Comment by yuya373** [comment]
> I move my laptop from ethernet to WiFi

Does this cause reconnection?
Currently, when reconnection happens, fetch all messages from server and then, delete all messages from buffer and then insert all fetched messages to buffer.

**Comment by yuya373** [comment]
I confirmed reconnection cause this issue, fix #351.
if there are any other cause, reopen this issue.

**Comment by matthew-piziak** [comment]
Awesome! Thank you so much!
