### ISSUE TITLE
Send Message Programmatically

### ISSUE THREAD

**Issue by jasonmj** [yuya373/emacs-slack#360]
Is it possible to send a message to a channel programmatically with Elisp? 

`slack-message-send` offers a similar functionality to what I'm looking for, but it requires the user to input details interactively.

**Comment by yuya373** [comment]
```lisp
(mapcar (lambda (team) (cons (oref team id) (oref team name)))
        slack-teams)

(let* ((channel-id "")
       (team-id "")
       (message "")
       (team (slack-team-find team-id)))
  (slack-message-send-internal message channel-id team))
```

**Comment by jasonmj** [comment]
Thanks so much for your response. 

I gave this code a try with my channel and team id, but unfortunately, I'm getting this error message: 
`slot-value: Wrong type argument: (or eieio-object class), nil, obj`

Here's the debug trace: 
`Debugger entered--Lisp error: (wrong-type-argument (or eieio-object class) nil obj)
  signal(wrong-type-argument ((or eieio-object class) nil obj))
  slot-value(nil message-id)
  slack-message-inc-id(nil)
  slack-message-send-internal("testing" "<my actual channel id>" nil)
  (let* ((channel-id "C0AA2AUQ3") (team-id "<my actual team id>") (message "testing") (team (slack-team-find team-id))) (slack-message-send-internal message channel-id team))
  eval-region(1 286)  ; Reading at buffer position 1
  funcall-interactively(eval-region 1 286)
  call-interactively(eval-region nil nil)
  command-execute(eval-region)
`

**Comment by yuya373** [comment]
Looks like `team` is `nil`. Please make sure that `team-id` is correct. Also, `slack-teams` should contain this id's team object.

**Comment by jasonmj** [comment]
Sorry, I didn't realize the team name and team id were different. It's working now. Thanks so much! 
For others who find this thread later, you can get the team id and the channel id by following these steps: 

1. To get channel id, run M-x `slack--get-channel-id` from inside the desired channel. 
2. To get the team id, visit https://api.slack.com/methods/team.info/test, select your team, and click "Test Method". 

Thanks again, @yuya373 for your help. I really enjoy using Emacs Slack!

**Comment by jasonmj** [comment]
Bummer, this code stopped working after a recent update. It appears that slack-message-send-internal expects an object for the channel instead of a string. Here's the backtrace I'm getting: 

`Debugger entered--Lisp error: (wrong-type-argument (or eieio-object class) "<my actual channel id>" obj)
  signal(wrong-type-argument ((or eieio-object class) "<my actual channel id>" obj))
  eieio-oref("<my actual channel id>" id)
  slack-message-send-internal("test" "<my actual channel id>" #<slack-team slack-team>)
  (let* ((channel-id "<my actual channel id>") (team-id "<my actual team id>") (message msg) (team (slack-team-find team-id))) (slack-message-send-internal message channel-id team))`

**Comment by yuya373** [comment]
This will work.

```lisp
(let* ((channel-id "")
       (team-id "")
       (message "")
       (team (slack-team-find team-id))
       (channel (slack-room-find channel-id team)))
  (slack-message-send-internal message channel team))
```

**Comment by jasonmj** [comment]
Excellent, that worked. Thanks so much!

**Comment by fullsteamlabs** [comment]
This code has been working for a long time, but a recent update broke it again. I'm getting this error now:  

Symbol’s value as variable is void: slack-teams

when this code runs: 
```(mapcar (lambda (team) (cons (oref team id) (oref team name)))
					slack-teams)```

Is there a quicks fix for whatever changed with the variable `slack-teams`?

**Comment by fullsteamlabs** [comment]
Figured it out, replacing `slack-teams` with `(hash-table-values slack-teams-by-token)` resolves the issue.
