### ISSUE TITLE
Sending message to channel before joining

### ISSUE THREAD

**Issue by creichert** [yuya373/emacs-slack#362]
I have a Slack team that uses "Drift", an on-site support chat service. When we receive a Drift message, it is sent to Slack where we can manage the conversion. The basic flow is:

- Use submits chat on site
- The message is sent to our Slack teams "#support" channel by the Drift bot
- A new _dynamically_ named channel is created for `z-username-1234`.

In the Slack web app

There's two problems:

1. I can select the `z-username-1234` channel easily w/ `slack-select-rooms`. However, if I don't `slack-channel-join` first, any message I send to the channel is lost without any error messages or blocking at all. 
    I have to explicitly do a `slack-channel-join`. This has caused me to lose a few bigger drafted messages I was planning to send  in response to a support request.

2. I can't seem to "join" the dynamic channel in the same way I'd be able to from the Slack Web UI:

    In the Slack web ui, if I click the z-visitor link, I join the corresponding channel:

    ![image](https://user-images.githubusercontent.com/526560/48284950-ad2b8200-e426-11e8-8f42-5116e8d86ad6.png)

    This link isn't present in emacs-slack, I'm assuming Slack treats it as a generic "#room" link, so maybe the regexp needs to be applied to attachments?
    
    ![image](https://user-images.githubusercontent.com/526560/48284913-9553fe00-e426-11e8-8fff-225f3903d398.png)
    
    When this message comes in, I do see this:

    ![image](https://user-images.githubusercontent.com/526560/48284920-9be27580-e426-11e8-8a7e-9a8894e7eb4e.png)

    This problem isn't really critical. I'm more concerned w/ 1.

Any assistance or advice would be appreciated.

---

As a side note, I have some patches for the slack-message-notifier module that should help easily configure keyword notifications and even notifications for dynamic channels such as the use-case above.

**Comment by yuya373** [comment]
## Cause

1. We can't send message without joining team
2. Handle channel name regexp, but didn't attach link to channel name

These are fixed by above pull requests.  

- join channel before send message unless joined
- add keymap and face to channel name

Thanks!

**Comment by creichert** [comment]
@yuya373 Wow, did not expect such a quick fix! Thanks a ton this is fantastic
