### ISSUE TITLE
`slack-im-select` failing silently, but only on _one_ DM

### ISSUE THREAD

**Issue by duncan-bayne** [yuya373/emacs-slack#367]
I can open a DM with any of the users on my Slack account, except for one particular individual:

1. `M-x slack-im-select`.
2. Select team: `Cogent`.
3. Pick a DM that 'works': `alex`.
4. See the message 'No Message in alex, fetching from server...`.
5. A moment afterwards, the buffer `*Slack - Cogent: alex` opens, with the DM contents.
6. `M-x slack-im-select`.
7. Pick the one DM that 'does not work': `danielle`.
8. I see the same sort of message: `No Message in danielle, fetching from server...`
9. ... but nothing else in `*messages*`, and no DM buffer ever opens.

**Comment by yuya373** [comment]
Please retry 6 ~ 9 with `toggle-debug-on-error` .
backtrace is helpful for debug.

**Comment by duncan-bayne** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p slack-channel-button-face)
  signal(wrong-type-argument (integer-or-marker-p slack-channel-button-face))
  #f(compiled-function (this) #<bytecode 0x205868da1>)(#<slack-message-buffer slack-message-buffer>)
  apply(#f(compiled-function (this) #<bytecode 0x205868da1>) #<slack-message-buffer slack-message-buffer>)
  #f(compiled-function (cl-cnm this) #<bytecode 0x205869601>)(#f(compiled-function (&rest cnm-args) #<bytecode 0x20b2a63d1>) #<slack-message-buffer slack-message-buffer>)
  apply(#f(compiled-function (cl-cnm this) #<bytecode 0x205869601>) #f(compiled-function (&rest cnm-args) #<bytecode 0x20b2a63d1>) #<slack-message-buffer slack-message-buffer>)
  #f(compiled-function (&rest args) #<bytecode 0x204ca4e99>)(#<slack-message-buffer slack-message-buffer>)
  apply(#f(compiled-function (&rest args) #<bytecode 0x204ca4e99>) #<slack-message-buffer slack-message-buffer> nil)
  slack-buffer-display(#<slack-message-buffer slack-message-buffer>)
  #f(compiled-function (buf) #<bytecode 0x20586ab99>)(#<slack-message-buffer slack-message-buffer>)
  #f(compiled-function (&rest ignore) #<bytecode 0x20541dbb5>)(t)
  #f(compiled-function (&rest rest) #<bytecode 0x20541dbcd>)(:data (:ok t :messages ((:type "message" :user "U0CPYJ7C0" :text ...
```

**Comment by duncan-bayne** [comment]
@yuya373 Please let me know if that's sufficient, or if you require the entire trace.  That trace contains our entire DM history, so I'd need to seek permission from Danielle to post it (or perhaps send it to you privately).
