### ISSUE TITLE
Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by vickenty** [yuya373/emacs-slack#37]
On latest master under Emacs 24.5.1 a `*Warnings*` occasionally pops up with the following message:
```
Error (websocket): in callback `on-message': Wrong type argument: stringp, nil
```

**Comment by yuya373** [comment]
anything backtrace?

**Comment by vickenty** [comment]
That is the only message I get, nothing related appears in *Messages* or elsewhere. Let me know if I can tweak anything on my end to produce more debugging information.

**Comment by yuya373** [comment]
for now M-x toggle-debug-on-error.
I will implement more handy debugging logger.


2016/01/12 1:15$B!"(BVickenty Fesunov <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by vickenty** [comment]
Global debug-on-error mode didn't catch this, but I was able to get the backtrace by setting `websocket-callback-debug-on-error`. I think this part of the backtrace is relevant:

```
  slack-room-find(nil)
  (let* ((item (plist-get payload :item)) (room (slack-room-find (plist-get item :channel))) (msg (slack-room-find-message room (plist-get item :ts))) (r-name (plist-get payload :reaction)) (r-count 1) (r-users (list (slack-user-find (plist-get payload :user)))) (reaction (make-instance (quote slack-reaction) :name r-name :count r-count :users r-users))) (if msg (progn (slack-message-append-reaction msg reaction) (slack-message-update msg t))))
  slack-ws-handle-reaction-added((:event_ts <<some-string>> :reaction <<some-string>> :item (:file <<some-string>> :type <<some-string>>) :user <<some-string>> :type <<some-string>>))
```

**Comment by yuya373** [comment]
thanks! #39 will fix this.

**Comment by vickenty** [comment]
`slack-room-find` still dies if called with nil argument, and that still happens if reaction did not come from a room.
```
slack-room-find(nil)
(let* ((item (plist-get payload :item)) (room (slack-room-find (plist-get item :channel)))) (if room (let ((msg (slack-room-find-message room (plist-get item :ts)))) (if msg (let* ((r-name (plist-get payload :reaction)) (r-count 1) (r-users (list ...)) (reaction (make-instance ... :name r-name :count r-count :users r-users))) (slack-message-append-reaction msg reaction) (slack-message-update msg t))))))
slack-ws-handle-reaction-added((:event_ts <<some-string>> :reaction <<some-string>> :item (:file <<some-string>> :type <<some-string>>) :user <<some-string>> :type <<some-string>>))
```

**Comment by yuya373** [comment]
https://api.slack.com/events/reaction_added
I tried three types reaction_add event above page with `(setq websocket-callback-debug-on-error t)`, could not catch errors.

**Comment by vickenty** [comment]
[Here](https://github.com/yuya373/emacs-slack/blob/40b3e39e21d07746f983b3d9b95330b587bb23d6/slack-websocket.el#L137):
```
 (room (slack-room-find (plist-get item :channel))))
```
`slack-room-find` is called with result of `plist-get`, which, as I understand it, returns `nil` if `:channel` is not in the `item`, and, according to the docs it is not when reaction happens to a file.

If I eval `(slack-room-find nil)` manually in the scratch buffer, it gives me the same error. Can it be that it doesn't crash in Emacs 25 when called with `nil`?

**Comment by yuya373** [comment]
yes, I eval `(slack-room-find nil)` manually, it returns nil.

```
(defun slack-room-find (id)
  (cl-labels ((find-room (room)
                         (string= id (oref room id))))
    (cond
     ((string-prefix-p "C" id) (cl-find-if #'find-room slack-channels))
     ((string-prefix-p "G" id) (cl-find-if #'find-room slack-groups))
     ((string-prefix-p "D" id) (cl-find-if #'find-room slack-ims)))))
```

`slack-room-find` use `string-prefix-p`, according to [this](https://github.com/emacs-mirror/emacs/commit/5697ca55cb79817a6704c344cc76d866ee2e1699) commit
```
(compare-strings "G" 0 1 nil
                 0 1 )
```
above raise this error
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  compare-strings("G" 0 1 nil 0 1)
  eval((compare-strings "G" 0 1 nil 0 1) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```
I dont know that commit is included under Emacs 25 or not, Emacs 25 does not raise error because of `(if (> prefix-length (length string)) nil ...`.

**Comment by yuya373** [comment]
anyway I will fix `(slack-room-find nil)`
