### ISSUE TITLE
slack-ws-close error

### ISSUE THREAD

**Issue by aminb** [yuya373/emacs-slack#374]
```
funcall-interactively: Wrong number of arguments: (1 . 2), 0
```

With the recent changes (specifically probably a32b5f4) calling `slack-ws-close` without arguments as before doesn't work anymore, since there's now a required non-optional `ws` argument. This makes `slack-ws-close` unusable in keybindings.

**Comment by yuya373** [comment]
Thanks!

**Comment by aminb** [comment]
Cheers, thanks for the fix!
