### ISSUE TITLE
Emacs-Slack Crashes

### ISSUE THREAD

**Issue by shoichit** [yuya373/emacs-slack#385]
Hi there,

I just installed Emacs-Slack on Emacs version 26.1 on Windows 10 (Gnupack), Slack package folder shows "slack-20181204.1211". I just was able to use a few times but it started crashing after I set "use-package" like below in my init.el rather than manually running "slack-register-team" and then copy and paste info. (I also installed "use-package" itself) 

It crashes at or after showing "Contacting host: emoji.slack-edge.com" after running "slack-start". Please help. I started liking this program and stopped working and I tried to do it the way I used to do but it no longer works and crashes at the same place. Setting  toggle-debug-on-error" didn't stop the crash. 

(use-package slack
  :commands (slack-start)
  :init
  (setq slack-buffer-emojify t)
  (setq slack-prefer-current-team t)
  :config
  (slack-register-team
   :name "emacs-slack"
   :default t
   :client-id "xxxx..."
   :client-secret "xxxx..."
   :token "xoxp-xxx..."
   :full-and-display-names t)
)

**Comment by yuya373** [comment]
I'm using this package on mac OS and Linux, did not encounter crashes.
So I think that this is an OS specific problem.
I do not have a Windows machine, so I am not sure, I think it is caused by `temporary-file-directory`,` write-region`, `delete-file`, and so on.

https://github.com/yuya373/emacs-slack/blob/develop/slack-image.el#L34
https://github.com/yuya373/emacs-slack/blob/develop/slack-request.el#L319
https://github.com/yuya373/emacs-slack/blob/develop/slack-request.el#L309

**Comment by shoichit** [comment]
Thank you for trying to help. I tried those functions by writing these below. They do work fine when I run them in a temp buffer. (Note: FYI, "temporary-file-directory" returns "/tmp/". )

--
(write-file
 (concat (temporary-file-directory) "temp.txt"))

(delete-file
 (concat (temporary-file-directory) "temp.txt"))
--

I set the following below. I just wonder setting the default file mode causes any issue. But setting it 777 didn't really change anything.)

(use-package server
  :init
  (set-default-file-modes ?\700) ; this is necessary to avoid an error.
  :config
  (unless (server-running-p)
    (server-start)))

**Comment by yuya373** [comment]
I tried below snippet in  Windows7 with virtualbox, and works fine.

if you comment out [this line](https://github.com/yuya373/emacs-slack/blob/master/slack-authorize.el#L75) and still crash, `slack-download-emoji` is not cause.
Please try this?

``` lisp
;;; -*- lexical-binding: t; -*-
(require 'request)

(with-temp-buffer
  (insert "Foo")
  (mm-write-region (point-min) (point-max)
                   (expand-file-name (concat temporary-file-directory "foo.txt"))
                   nil nil nil 'binary t))

(let ((url "https://.../foo.png")
      (token "xoxs-....")
      (sync t) ;; also (sync nil) works fine
      (newname (expand-file-name (concat temporary-file-directory "foo.png"))))
  (cl-labels
      ((on-success (&key _data &allow-other-keys)
                   (message "SUCCESS"))
       (on-error (&key error-thrown symbol-status response _data)
                 (message "Error Fetching Image: %s %s %s, url: %s"
                          (request-response-status-code response)
                          error-thrown symbol-status url)
                 (if (file-exists-p newname)
                     (delete-file newname))
                 (cl-case (request-response-status-code response)
                   (403 nil)
                   (404 nil)
                   (t (message "[Error] %S, %S" error-thrown symbol-status))))
       (parser () (mm-write-region (point-min) (point-max)
                                   newname nil nil nil 'binary t)))
    (let* ((url-obj (url-generic-parse-url url))
           (need-token-p (and url-obj
                              (string-match-p "slack"
                                              (url-host url-obj))))
           (use-https-p (and url-obj
                             (string= "https" (url-type url-obj)))))
      (request
       url
       :success #'on-success
       :error #'on-error
       :parser #'parser
       :sync sync
       :headers (if (and token use-https-p need-token-p)
                    (list (cons "Authorization" (format "Bearer %s" token))))))))

```
