### ISSUE TITLE
How to get :client-id from web browser?

### ISSUE THREAD

**Issue by stardiviner** [yuya373/emacs-slack#387]
I followed README guide to get client id and token, but don't know hot to get cliekt secret.

**Comment by yuya373** [comment]
if you get token in [this](https://github.com/yuya373/emacs-slack#1-from-request-payload) way, you don't have to get client-id and client-secret.
from [this](6063da57b876e7a49feb4a90997c63d479afb370) commit, `slack-register-team` requires either client-id and client-secret or token.

**Comment by stardiviner** [comment]
Thanks. I only applied token like this:
```elisp
(slack-register-team :name "clojurians"
                               :default t
                               ;; :client-id "e................."
                               :token "xoxs-..........."
                               :subscribed-channels '(announcements
                                                      beginners
                                                      clojuer clojurescript
                                                      cider emacs sql)
                               :full-and-display-names t)
```
But I got an error: #388
