### ISSUE TITLE
Unable to open slack-channel buffer.

### ISSUE THREAD

**Issue by Bee-Mar** [yuya373/emacs-slack#391]
I know there have been previous issues that are very similar to this one, but I'm not sure if anyone else has had this issue very recently and/or resolved the issue. I have tried all the previous suggestions I was able to find on forums and other git issues (ie. changing "slack-if-let" to "if-let"), and none have worked.

When selecting `slack-channel-select`, the channel buffer does not display. Instead, I receive the following error message: `No Message in <channel-name>, fetching from server...`

The only consistent function that seems to work for me is `slack-im-select`. 

EDIT: I did some more testing, and the issue I seem to be having is solely affecting the non-default channels. I can open `general` and `random` without any issue, but I'm unable to open custom named channels.

EDIT No.2: Could this be happening  because the channels are not owned by the workspace admin?

Emacs version: 25.2.2
OS: Ubuntu 18.04

**Comment by jasonmj** [comment]
I was seeing this same issue after re-installing Emacs. I used `M-x toggle-debug-on-error` to figure out why the buffer wasn't loading and it turns out the failure (for me at least) was that I did not have company-emoji installed.
