### ISSUE TITLE
No notice in modeline when new message posted to thread

### ISSUE THREAD

**Issue by dmusican** [yuya373/emacs-slack#396]
Whenever a new message gets posted to a channel, I see that in a parenthesized indicator on the modeline (i.e. from tracking.el). That does not appear when a new reply is added to a thread. Any ideas on how to config things so I can get some kind of indication when replies are posted to threads?

**Comment by matthew-piziak** [comment]
I have the same issue.

**Comment by yuya373** [comment]
We have to call `tracking-add-buffer` like [this](https://github.com/yuya373/emacs-slack/blob/master/slack-message-buffer.el#L663) in [this](https://github.com/yuya373/emacs-slack/blob/master/slack-message-buffer.el#L870) and [this](https://github.com/yuya373/emacs-slack/blob/master/slack-message-buffer.el#L861) functions.
I don't use tracking.el so someone implement and make a pull request
