### ISSUE TITLE
Shorten Buffer Name

### ISSUE THREAD

**Issue by nshi** [yuya373/emacs-slack#413]
The current buffer names are in the form `*Slack - Team : Room`. Is it possible to shorten it by removing the prefix "*Slack - ", or even remove the team name as well? It takes up quite a lot of space in the mode line and the buffer list, making it hard to know what buffer it is when it's truncated in the buffer list. For cases where user is just using a single team, I think it's fine to just have the room name. If team name has to be displayed, maybe let user define the display name for the team.

**Comment by nshi** [comment]
Awesome. Thanks for the tip, @jkdufair. This works.

**Comment by jasonmj** [comment]
I'm trying to get the code shown above to work, but apparently I'm doing something wrong. Perhaps it no longer works?

**Comment by jasonmj** [comment]
I came back to this and managed to get it working. Here's the code I'm using in my `:config` to shorten buffer names to the room name only: 
```
(cl-defmethod slack-buffer-name ((this slack-message-buffer))
    (slack-if-let* ((team (slack-buffer-team this))
                    (room (slack-buffer-room this))
                    (room-name (slack-room-name room team)))
        room-name))
```
