### ISSUE TITLE
Feature request: visible thread in channel messages

### ISSUE THREAD

**Issue by aladine** [yuya373/emacs-slack#418]
2 features I wish to have in channel messages: 
1. All the messages under a thread could be visible in the same interface. It is similar to *Visible thread*  in https://refined.chat/ 
2. When I enable slack-buffer-emojify,  emoji image in user name should be render in small size. Now it just plainly big and break the UI. Eventually I decide to disable emojify since I haven't found any way to fix it.

**Comment by yuya373** [comment]
Visible Threads is a really good feature. It may be implemented in the future.

You can disable emojify in message header by adding inhibit function like below

```emacs-lisp
  (defun slack-emojify-header-text-p (_match beg _end)
    (eq 'slack-message-output-header
        (get-text-property beg 'face)))
  (add-to-list 'emojify-inhibit-functions #'slack-emojify-header-text-p)
```

**Comment by yuya373** [comment]
But in my environment, emoji in user name rendered in small size.
<img width="383" alt="スクリーンショット 2019-03-22 2 01 32" src="https://user-images.githubusercontent.com/3055271/54770420-8720b480-4c46-11e9-9783-b78cb3bc5b2e.png">

**Comment by aladine** [comment]
Thanks i will try that. Actually, the problem only happened with certain emojis. This screenshot is for emoji :pickle:
<img width="734" alt="Screen Shot 2019-03-22 at 9 59 46 am" src="https://user-images.githubusercontent.com/287410/54790316-ccb2a100-4c89-11e9-9d3a-35ea697452e7.png">

**Comment by yuya373** [comment]
Is this emoji rendered correctly as reaction?
I think your Emacs build without imagemagick support, so emojify can't resize emoji image file.
https://github.com/iqbalansari/emacs-emojify/blob/master/emojify.el#L958

**Comment by aladine** [comment]
> Is this emoji rendered correctly as reaction?
> I think your Emacs build without imagemagick support, so emojify can't resize emoji image file.
> https://github.com/iqbalansari/emacs-emojify/blob/master/emojify.el#L958

I think it is resolved after i install imagemagick. 
For some icons imagemagick failed to render, it becomes plain text. Example the pickle emoji above. for others, UI renders perfectly.

**Comment by matthew-piziak** [comment]
Custom emoji for me become the Slack logo. I have Emacs compiled with imagemagick support. Scaling works fine.

**Comment by yuya373** [comment]
@aladine 
Could you upload a pickle image to this issue for investigation?
Did you build Emacs with `--with-imagemagick` ?

@matthew-piziak 
your custom emoji may be broken alias, can you show me `emoji.list` output?
https://github.com/yuya373/emacs-slack/pull/415

**Comment by aladine** [comment]
@yuya373 I just rebuilt my emacs by using emacs-plus. The problem is solved now. Hooray
Thank you so much for your help.

**Comment by matthew-piziak** [comment]
@yuya373 Huh, weird, if I access `https://slack.com/api/emoji.list` I get an `not_authed` error even though I'm logged in.

**Comment by yuya373** [comment]
@matthew-piziak  
It seems `token` is needed in query parameter even logged in.
`https://slack.com/api/emoji.list?pretty=1&token=xoxs-...`
