### ISSUE TITLE
How to disable markdown fontlock?

### ISSUE THREAD

**Issue by jaor** [yuya373/emacs-slack#430]
emacs-slack unconditionally fontifies incoming messages as markdown, removing markup characters in the process.  but in many occasions those characters are meaningful and not intended as markup: e.g., someone writes `AN_ENV_VARNAME` or a URL such as `http://foo.com/bar_msg_foo.html`, etc., and those `_` are gone (well, they're invisible).  would it be complicated to add an option to disable markdown fontlock altogether? i've tried to just remove slack-mrkdwn-add-face from the local lui-pre-output-hook list, but it doesn't seem to work.

thanks a lot for your work on this package, it's the only way i could ever use slack! :)

**Comment by yuya373** [comment]
mrkdown markup will be disabled by overwriting `slack-mrkdwn-add-face` like below

```emacs-lisp
(defun slack-mrkdwn-add-face () 
  ;; no-op )
```
or 

```emacs-lisp
(add-hook 'slack-message-buffer-mode-hook
          '(lambda () (remove-hook 'lui-pre-output-hook 'slack-mrkdwn-add-face t))
```

However, these markup should be fixed.
