### ISSUE TITLE
Viewing file attachments in Emacs

### ISSUE THREAD

**Issue by matthew-piziak** [yuya373/emacs-slack#440]
If I press `RET` on a file link (`slack-file-display`), it opens a buffer with the name, size, and type of the file, but it does not display the contents. It also has a link to the file location, but that navigates to the Slack web client.

Is it possible for Emacs to download and open the file directly? I could not find the functionality.

**Comment by yuya373** [comment]
We can currently view image files and email files in Emacs, but other files are showing links to slack web clients.

**Comment by matthew-piziak** [comment]
There's no way to download the file directly? Is it a permissioning problem?

**Comment by yuya373** [comment]
Slack provide `url_private_download`, we can download file with this url.
But function is not implemented yet.

**Comment by matthew-piziak** [comment]
Got it, thank you!

**Comment by matthew-piziak** [comment]
You rock!

**Comment by unhammer** [comment]
The download link is handy, but then I have to manually navigate to the file and open it – how about a "Download and open" button?

**Comment by symbiont-matthew-piziak** [comment]
@unhammer Below the Download and Actions Button there should be a link which opens the file.

**Comment by unhammer** [comment]
@symbiont-matthew-piziak when I click that, it seems to call browse-url on it, which for me opens it in eww where I am of course not logged into slack

**Comment by symbiont-matthew-piziak** [comment]
@unhammer Huh, in my case it's a PDF and Emacs just opens it directly.
