### ISSUE TITLE
channel list update fails with `(invalid-slot-type slack-channel creator string nil)`

### ISSUE THREAD

**Issue by kushal-kumaran** [yuya373/emacs-slack#442]
The `slack-group` class requires `creator` to be a string. I'm not sure why the `creator` is coming up `nil`, but using the slack web interface shows it to be a non-existent user.

    slack-room-create((:id "<room-id-removed>" :name "<name-removed>" :is_channel t :is_group :json-false :is_im :json-false :created 1465419894 :is_archived :json-false :is_general :json-false :unlinked 0 :name_normalized "<name-removed>" :is_shared :json-false :parent_conversation nil :creator nil :is_moved 2 :is_ext_shared :json-false :is_org_shared :json-false :shared_team_ids ("<team-id-removed>") :pending_shared nil :is_pending_ext_shared :json-false :is_member :json-false :is_private :json-false :is_mpim :json-false :topic (:value "<topic-removed>" :creator nil :last_set 1465419894) :purpose (:value "<purpose-removed>" :creator nil :last_set 1465419894) :previous_names nil ...) slack-channel)

Changing the type of `creator` in the `slack-group` class to have type `(or string null)` fixes the crash.

**Comment by yuya373** [comment]
> but using the slack web interface shows it to be a non-existent user.

Oh, Thanks!
