### ISSUE TITLE
Trouble killing emacs-slack

### ISSUE THREAD

**Issue by shader** [yuya373/emacs-slack#443]
I'm having trouble with emacs-slack (love the project though), primarily because I think I have my emacs too overloaded to meet the timeout requirements for the ws connection timeouts.

Unfortunately, I can't seem to find a way to turn it off, outside of killing emacs.

If I try running `slack-ws-close`, it silently does... nothing, I guess, and keeps reconnecting. Same if I manually kill the websocket process, or delete the slack team with `slack-delete-team`.

How do I _kill_ the slack client once and for all?

**Comment by yuya373** [comment]
I executed `slack-ws-close`, close all websocket connections and no reconnecting.
There may be some glitches in `slack-ws-close` when emacs is overloaded.

to inhibit auto-reconnecting set `:reconnect-auto` to `nil` and expand websocket ping timeout set `:check-ping-timeout-sec` to large integer value. 

```emacs-lisp
  (slack-register-team
   :default nil
   :name "emacs-slack"
   :check-ping-timeout-sec 99 ;; default 20
   :reconnect-auto nil
...
)
```
