### ISSUE TITLE
Messages sent to threads do not appear until refreshed

### ISSUE THREAD

**Issue by matthew-piziak** [yuya373/emacs-slack#448]
If I am in a thread buffer and send a message, and then select `n` (no) when deciding to send the message to the parent channel, then my message does not appear in the thread. To see it again, I have to kill the thread buffer and then click on the thread link on the parent channel to open and refresh it.

**Comment by yuya373** [comment]
Thanks for reporting!

**Comment by matthew-piziak** [comment]
Wow, you're fast. :+1:
