### ISSUE TITLE
Update README with instructions on how to use emacs-slack?

### ISSUE THREAD

**Issue by seanhagen** [yuya373/emacs-slack#45]
Right now the README has instructions on how to connect Emacs to Slack with this package ( which work great, I'm all connected ), but no instructions on how to use the package.

I've got no idea on how to send messages, and I can't test very much because I can't switch channels due to #44. Maybe once that bug is fixed and I'm able to play around with it, I'll be able to write docs and do a PR.

**Comment by kostajh** [comment]
@yuya373 can correct me if I'm wrong, but I think the issue is that the package isn't totally ready for every day use just yet. There seem to be a lot of working components but it's not unified into a single package just yet.

**Comment by yuya373** [comment]
@kostajh I'm using only this package for chatting by slack during my work. so I think ready for every day use.

**Comment by mattford63** [comment]
The latest updates are good enough of me to use as my main client also :-)

**Comment by kostajh** [comment]
OK, in that case, I agree with @seanhagen that an updated README on usage, or a short screencast might be helpful.

**Comment by kostajh** [comment]
@seanhagen have a look at the Spacemacs layer I created, you should be able to enable that layer and be good to go with some basic keybindings and configuration in place. https://github.com/syl20bnr/spacemacs/pull/4821

**Comment by ibrahima** [comment]
So for some reason I had to run slack-select-rooms and then tab complete to join a channel (I think there's whitespace in front of the names, which should maybe be stripped?). Slack-channel-join doesn't seem to do what I expect or want.

**Comment by seanhagen** [comment]
Nothing in two years, I'm closing this as part of a "clean out my GH issues list" :stuck_out_tongue:
