### ISSUE TITLE
Constant Websocket PING Timeouts

### ISSUE THREAD

**Issue by noonker** [yuya373/emacs-slack#458]
**Describe the bug**
Recently after starting emacs-slack I get continuous ping timeouts. 

[2019-06-14 12:15:52] [warn] [COMPANY] Slack Websocket PING Timeout.
[2019-06-14 12:16:02] [warn] [COMPANY] Reconnecting... [1/360]
[2019-06-14 12:16:03] [info] [COMPANY] Slack Websocket Is Ready!
[2019-06-14 12:16:08] [info] [COMPANY] Slack Channel List Updated
[2019-06-14 12:16:08] [info] [COMPANY] Slack Group List Updated
[2019-06-14 12:16:08] [info] [COMPANY] Slack Im List Updated
[2019-06-14 12:16:08] [info] [COMPANY] Fetching users... [90/157]
[2019-06-14 12:16:09] [info] [COMPANY] Fetching users... [150/157] 

I've tried upping the ping timeout with no success
`(setq slack-request-timeout 120) `

This happens on every server I have configured. No additional information is logged when enabling `set-debug-on-error` 

**To Reproduce**
1. Start emacs slack with 'slack-start'
2. Wait a minute or so and the slack ws will ping timeout and reconnect.

**Environment:**
 - OS: Fedora 28
 - Emacs Version: 26.1
 - emacs-slack Version: 20190612.1301

**Comment by yuya373** [comment]
check pong message from slack in Slack Event Log buffer.
these comments may be help.
https://github.com/yuya373/emacs-slack/commit/e464663a6a68db0b37878e4d27598d6aaf28d98d#commitcomment-33925917
https://github.com/yuya373/emacs-slack/commit/e464663a6a68db0b37878e4d27598d6aaf28d98d#commitcomment-33929099
https://github.com/yuya373/emacs-slack/commit/e464663a6a68db0b37878e4d27598d6aaf28d98d#commitcomment-33929340

**Comment by noonker** [comment]
It does look like the server is missing some of the ping messages or the pong messages are occasionally getting lost. Would it make sense to do a retry ping before resetting the connection?

[Outgoing] [2019-06-14 13:27:03] (:id 154 :type "ping" :time "1560536823.1600053")
[Incoming] [2019-06-14 13:27:03] (:type "pong" :time "1560536823.1600053" :reply_to 154)
[Outgoing] [2019-06-14 13:27:13] (:id 155 :type "ping" :time "1560536833.2068386")
[Incoming] [2019-06-14 13:28:16] (:type "presence_change" :presence "away" :user "UUUU")
[Incoming] [2019-06-14 13:28:31] (:type "presence_change" :presence "active" :user "UUUU1")

**Comment by yuya373** [comment]
> Would it make sense to do a retry ping before resetting the connection?

It seems hacky to me,  the server has responsibility to fix the problems. 
 Adding custom variable to stop close websocket connection and reconnecting when pin-pong timeout is easy workaround.

**Comment by jaor** [comment]
just confirming that i see this too, very, very frequently.  FWIW, slack's status page claims service is working without issues by now, so i am not sure if we can trust their servers :( 

also, i've tried to change the timeout to 60 with `:check-ping-timeout-check 60` in `register-team`, but i still see reconnections every 20 seconds: isn't that the right parameter?

**Comment by yuya373** [comment]
reconnection occurs every `reconnect-after-sec` seconds.
run `slack-ws-on-ping-timeout` after `check-ping-timeout-sec` seconds after sending ping to server.

**Comment by jaor** [comment]
On Sun, Jun 16 2019, Yuya Minami wrote:

> reconnection occurs every reconnect-after-sec seconds.

Isn't that a timer that only is triggered if a connection attempt fails
(or if the connection is lost)?  If so, in this case it wouldn't be
relevant because connections always succeed at the first attempt and
their never lost (they just miss pongs).

> run slack-ws-on-ping-timeout after check-ping-timeout-sec seconds after sending ping to server.

So, if check-ping-timeout-sec is set to 60, I should at least see 60
seconds between 2 (re)connections, provided the (re)connections are
triggered by a lost pong, right?  But instead I see the client
connecting again and again every 20 seconds.  So it is as if reconnect
is being triggered by other causes in addition to ping/pong
failures... Actually, in the log below, you can see that after the
first PING timeout, there are 3 reconnections that don't seem to be
triggered by a PING timeout:

```
[2019-06-16 20:53:27] [warn] [COMPANY] Slack Websocket PING Timeout.
[2019-06-16 20:53:37] [warn] [COMPANY] Reconnecting... [1/360]
[2019-06-16 20:53:39] [info] [COMPANY] Slack Websocket Is Ready!
[2019-06-16 20:53:42] [info] [COMPANY] Slack Channel List Updated
[2019-06-16 20:53:42] [info] [COMPANY] Slack Group List Updated
[2019-06-16 20:53:42] [info] [COMPANY] Slack Im List Updated
[2019-06-16 20:53:42] [info] [COMPANY] Fetching users... [30/53]
[2019-06-16 20:54:00] [warn] [COMPANY] Reconnecting... [1/360]
[2019-06-16 20:54:01] [info] [COMPANY] Slack Websocket Is Ready!
[2019-06-16 20:54:04] [info] [COMPANY] Slack Channel List Updated
[2019-06-16 20:54:04] [info] [COMPANY] Slack Group List Updated
[2019-06-16 20:54:04] [info] [COMPANY] Slack Im List Updated
[2019-06-16 20:54:04] [info] [COMPANY] Fetching users... [30/53]
[2019-06-16 20:54:21] [warn] [COMPANY] Reconnecting... [1/360]
[2019-06-16 20:54:23] [info] [COMPANY] Slack Websocket Is Ready!
[2019-06-16 20:54:26] [info] [COMPANY] Slack Channel List Updated
[2019-06-16 20:54:26] [info] [COMPANY] Slack Group List Updated
[2019-06-16 20:54:26] [info] [COMPANY] Slack Im List Updated
[2019-06-16 20:54:26] [info] [COMPANY] Fetching users... [30/53]
[2019-06-16 20:57:34] [warn] [COMPANY] Slack Websocket PING Timeout.
[2019-06-16 20:57:44] [warn] [COMPANY] Reconnecting... [1/360]
[2019-06-16 20:57:45] [info] [COMPANY] Slack Websocket Is Ready!
[2019-06-16 20:57:48] [info] [COMPANY] Slack Channel List Updated
[2019-06-16 20:57:48] [info] [COMPANY] Slack Group List Updated
[2019-06-16 20:57:48] [info] [COMPANY] Slack Im List Updated
[2019-06-16 20:57:49] [info] [COMPANY] Fetching users... [30/53]
```

**Comment by yuya373** [comment]
> So it is as if reconnect
is being triggered by other causes in addition to ping/pong
failures...

Looks like it...

In situations other than ping-pong timeouts, `slack-ws-reconnect` is called in these situations.
- https://github.com/yuya373/emacs-slack/blob/master/slack-websocket.el#L167
- https://github.com/yuya373/emacs-slack/blob/master/slack-websocket.el#L341

when `(setq slack-log-level 'debug)` , is there any other messages?

**Comment by jaor** [comment]
On Sun, Jun 16 2019, Yuya Minami wrote:

>     So it is as if reconnect
>     is being triggered by other causes in addition to ping/pong
>     failures...
>    
> Looks like it...
>
> In situations other than ping-pong timeouts, slack-ws-reconnect is called in these situations.
>
>   • https://github.com/yuya373/emacs-slack/blob/master/slack-websocket.el#L167
>   • https://github.com/yuya373/emacs-slack/blob/master/slack-websocket.el#L341
>
> when (setq slack-log-level 'debug) , is there any other messages?

I've been trying to reproduce the situation without success.  Perhaps I
had restarted or reloaded slack more than once and somehow two timers
were active, or my network was genuinely flaky.  Be as it may, today I
just see reconnections due to missing pongs.

What I observe in the logs is that it is never the case that the pong is
late: it is either received almost instantaneously or never
received. IMHO, a retry wouldn't be hacky: a lost packet might not be
the server's fault, it could be the network in between losing it, so it
seems fair to give the protocol a second chance.

Thanks!

**Comment by yuya373** [comment]
> IMHO, a retry wouldn't be hacky: a lost packet might not be
the server's fault, it could be the network in between losing it, so it
seems fair to give the protocol a second chance.

If a normal message fails to deliver, reconnect and re-send the message. But this is a ping pong message used to verify remote endpoint is still responsive. So I think it's enough to reconnect without retrying the ping message.

**Comment by jaor** [comment]
On Mon, Jun 17 2019, Yuya Minami wrote:

>     IMHO, a retry wouldn't be hacky: a lost packet might not be
>     the server's fault, it could be the network in between losing it, so it
>     seems fair to give the protocol a second chance.
>    
> If a normal message fails to deliver, reconnect and re-send the
> message. But this is a ping pong message used to verify remote
> endpoint is still responsive. So I think it's enough to reconnect
> without retrying the ping message.

Well, reconnection is a must heavier operation that resending a ping,
and it actually sometimes takes enough time to disrupt my editing
session (every now and then there's a pause for instance downloading
statuses when a new connection is made).  It's also disruptive in that
it produces several messages in the minibuffer, which interfere with the
normal workflow with noise if just at that moment i am using the
minibuffer for some reason.

**Comment by jaor** [comment]
Yesterday, I got an update for the websocket package from MELPA, and since then I am not getting missing pongs anymore.  Maybe it's a coincidence and what happened is that the Slack guys just fixed their servers, but, be it as it may, the fact is that this problem seems to have disappeared , at least for the last 24 hours.

**Comment by yuya373** [comment]
>  It's also disruptive in that
it produces several messages in the minibuffer, which interfere with the
normal workflow with noise if just at that moment i am using the
minibuffer for some reason.

Overwriting `slack-message-logger` as below would make the minibuffer quieter.

```emacs-lisp
(defun slack-message-logger (message level team))
```

**Comment by jaor** [comment]
On Fri, Jun 21 2019, Yuya Minami wrote:

>     It's also disruptive in that
>     it produces several messages in the minibuffer, which interfere with the
>     normal workflow with noise if just at that moment i am using the
>     minibuffer for some reason.
>    
> Overwriting slack-message-logger as below would make the minibuffer quieter.
>
> (defun slack-message-logger (message level team))

Thanks for the tip.  I've also found that setting slack-log-level to
'warn silences most of the interruptions.

**Comment by yuya373** [comment]
> Yesterday, I got an update for the websocket package from MELPA, and since then I am not getting missing pongs anymore. Maybe it's a coincidence and what happened is that the Slack guys just fixed their servers, but, be it as it may, the fact is that this problem seems to have disappeared , at least for the last 24 hours.

I confirmed missing pongs in [this](https://github.com/ahyatt/emacs-websocket/commit/53bfd56e12d9d1384b8105aa2a6ea0d7bdacb7da) version.

**Comment by noonker** [comment]
This also does not appear to be an issue for me anymore. Feel free to close it unless you're using it to track some work.
