### ISSUE TITLE
Direct messages do not not raise a mode line alert

### ISSUE THREAD

**Issue by mattford63** [yuya373/emacs-slack#46]
So close now to being my main client :-)

Is it possible for the mode line to raise notification of DMs like channels do?

Also I'd like to disable the notification on the mode-line of the notification channel - it's way way to busy in our environment.

**Comment by yuya373** [comment]
> Is it possible for the mode line to raise notification of DMs like channels do?

In my environment, channel, group, direct message, multiparty direct message is notified correctly.
I tried  `(setq alert-default-style 'mode-line)` and  `(setq alert-default-style 'notifier)`.



> Also I'd like to disable the notification on the mode-line of the notification channel - it's way way to busy in our environment.

remove channel to disable notification from `slack-room-subscription`.
channel and group messages are not notified unless channel name is no on the list.

**Comment by mattford63** [comment]
Hi I'm talking about the "[*S -n*]" mode line addition not so much the alert system.  Can DM's create an equivalent? Other rooms do.

**Comment by mattford63** [comment]
There seems to be issues with the various different ways of entering rooms/channels/IMs and alerting and message history.

I can't quite make it repeatable.  But I often don't get alerted for IMs.  I often don't see  the load previous messages.

I can't work out how to get rid of the "[*S - n*]" characters.

**Comment by yuya373** [comment]
> How should I leave a room/chat?

use `slack-channel-leave` or `slack-group-leave` to leave room/channel.
if simply hide room/chat buffer, I'm using `delete-window`.
if you want to kill buffer, eval below function, this will work.

```
(defun slack-buffer-kill ()
  (interactive)
  (with-current-buffer (current-buffer)
      (let ((room slack-current-room))
        (slack-room-update-last-read room
                                     (slack-message :ts "0")))
    (kill-buffer-and-window)))
```

After killing above function, no need to `slack-{im,channel}-list-update` I think.


> If I'm not all ready in a DM buffer then I don't seem to be alerted at all.

what is "all ready" means ?
there is no implementation for slack evnet "im_created", newly created direct message will not alerted.

> I can't work out how to get rid of the "[S - n]" characters in the mode-line.

what is "[S - n]" character?
I use alert with `(setq alert-default-style 'notifier)`, I don't get it.

**Comment by ryuslash** [comment]
Hey,

> After killing above function, no need to slack-{im,channel}-list-update I think.

Should that function perhaps be added to a buffer-local `kill-buffer-hook`?

>> If I'm not all ready in a DM buffer then I don't seem to be alerted at all.
>
> what is "all ready" means ?
> there is no implementation for slack evnet "im_created", newly created direct message will not alerted.

I think he means that he doesn't get notifications for DMs that he hasn't opened in a buffer yet.

>> I can't work out how to get rid of the "[S - n]" characters in the mode-line.
>
> what is "[S - n]" character?
> I use alert with (setq alert-default-style 'notifier), I don't get it.

Here I think he means the mode-line notification part of lui.el, or actually tracking.el, which always shows which rooms have unread messages. When messages come in it always shows there are new messages in the `*Slack - notifications*` buffer. I think we may be able to fix that by adding something to `tracking-ignored-buffers`. Unless we can throw away `*Slack - notifications*`, I don't really understand its function now that we use alert.el. *Or* we need to always pass a non-nil value for `not-tracking-p` when using `lui-insert` in the `*Slack - notifications*` buffer.

**Comment by yuya373** [comment]
> I think he means that he doesn't get notifications for DMs that he hasn't opened in a buffer yet.

Ok, I can receive notification with alert.el without open any slack buffer.
but, I didn't think about mode-line notification of lui.el.

> I think we may be able to fix that by adding something to tracking-ignored-buffers. Unless we can throw away *Slack - notifications*, I don't really understand its function now that we use alert.el. 

yes, I will remove *Slack - notifications* and its function.


> Should that function perhaps be added to a buffer-local kill-buffer-hook?

thanks!, I added in this [commit](https://github.com/yuya373/emacs- slack/commit/76e606a651855bdb0ac26b5e7babdef3a411cc96) and it seems working

**Comment by ryuslash** [comment]
>> I think we may be able to fix that by adding something to tracking-ignored-buffers. Unless we can throw away Slack - notifications, I don't really understand its function now that we use alert.el.
>
> yes, I will remove Slack - notifications and its function.
>
>> Should that function perhaps be added to a buffer-local kill-buffer-hook?
>
> thanks! I added in this commit and it seems working

Excellent :)

**Comment by ryuslash** [comment]
>> I think he means that he doesn't get notifications for DMs that he hasn't opened in a buffer yet.
>
> Ok, I can receive notification with alert.el without open slack buffer.
> but, I didn't think about mode-line notification of lui.el.

I think this is because we don't open a new buffer when a DM is received. If there is a buffer the message is displayed in it, but we don't open a new buffer. This means that no `lui-insert` is called and so tracking.el doesn't have anything to notify the user of.

I've also noticed that when I receive a DM and then open a buffer for it, only the unread messages are displayed, without any history.

I hope this helps a little.

**Comment by yuya373** [comment]
> I think this is because we don't open a new buffer when a DM is received. If there is a buffer the message is displayed in it, but we don't open a new buffer. This means that no lui-insert is called and so tracking.el doesn't have anything to notify the user of.

I understand. I will fix this sometime in the future. 

> I've also noticed that when I receive a DM and then open a buffer for it, only the unread messages are displayed, without any history.

thanks! I will fix this later. you helped me a lot!

**Comment by yuya373** [comment]
> I've also noticed that when I receive a DM and then open a buffer for it, only the unread messages are displayed, without any history.

#56 will fix this. thanks!

**Comment by catern** [comment]
> > I think this is because we don't open a new buffer when a DM is received. If there is a buffer the message is displayed in it, but we don't open a new buffer. This means that no lui-insert is called and so tracking.el doesn't have anything to notify the user of.
> 
> I understand. I will fix this sometime in the future.

Has this been fixed/this feature been added?

If not, is there some hook I could use to write my own function to open a new buffer when a DM is received?
