### ISSUE TITLE
[[Inquery]] Is there Something which Needs to Be Set to See "User is Typing…" Notifications?

### ISSUE THREAD

**Issue by WammKD** [yuya373/emacs-slack#460]
I have `slack-typing-visibility` set to `'frame` but I'm not seeing any sort of "This user is typing…" notifications in any of my Slack buffers.

Is there another setting I have to set that I just missed? I assumed that just having `slack-typing-visibility` not set to `'never` would get things to work if the focused buffer was a Slack buffer but I could easily just be mistaken.

Thanks!

**Comment by yuya373** [comment]
It's a bug! thanks for reporting.
#470 will fix this
