### ISSUE TITLE
slack-im-close is broken

### ISSUE THREAD

**Issue by finalpatch** [yuya373/emacs-slack#461]
**Describe the bug**

Using this command gives an error:

funcall-interactively: Symbol’s value as variable is void: team

**To Reproduce**
1. Go to a room
2. M-x slack-im-close
3. See error

**Backtrace**
```
Paste Backtrace if any.
Do not forget to mask confidential information. (e.g. token, message, ...)
```

**Expected behavior**

**Screenshots**

**Environment:**
 - OS: [e.g. macOS]
 - Emacs Version: [e.g. 25]
 - emacs-slack Version: [e.g. `9ffc86` (commit hash) or `20190519.716` (melpa version)]

**Additional context**

**Comment by yuya373** [comment]
I can't reproduce this error at 9ffc865097f5e4d779e2dace43b00a4a10305719 and master.
Is this error occurs after restarting Emacs?

**Comment by finalpatch** [comment]
Yes.  I'm using the melpa version

**Comment by finalpatch** [comment]
no long seen in latest version, closing
