### ISSUE TITLE
`slack-display-team-name` should apply to buffer name too

### ISSUE THREAD

**Issue by finalpatch** [yuya373/emacs-slack#465]
**Describe the bug**

even with slack-display-team-name set to nil,  slack buffer names still contain team names.

**To Reproduce**

set slack-display-team-name to nil
observe slack chat buffer names

**Backtrace**
```
Paste Backtrace if any.
Do not forget to mask confidential information. (e.g. token, message, ...)
```

**Expected behavior**

**Screenshots**

**Environment:**
 - OS: [e.g. macOS]
 - Emacs Version: [e.g. 25]
 - emacs-slack Version: [e.g. `9ffc86` (commit hash) or `20190519.716` (melpa version)]

**Additional context**

**Comment by yuya373** [comment]
Currently using buffer name to track message buffer, adding team name as a prefix to ensure uniqueness. 
If I remove the team name from the buffer name, I need to add another prefix
