### ISSUE TITLE
Slack using tramp connection when visiting a remote file. 

### ISSUE THREAD

**Issue by noonker** [yuya373/emacs-slack#466]
I'm having an issue where if I'm visiting a remote file via tramp then slack will use curl on the remote machine.

Reproduction:
  1. Visit a file in tramp
  2. run `(setq tramp-verbose 10)`
  3. Load a channel 
  4. In the tramp debug buffer you will see that the channel retrieval is happening over tramp and not locally. This is very slow. 

Any thoughts?

**Comment by yuya373** [comment]
If tramp set remote path to buffer's `default-directory`, `(expand-file-name "~/")` in [`request--curl`](https://github.com/abingham/emacs-request/blob/master/request.el#L966) may be remote home directory.
