### ISSUE TITLE
mark is not moved when entering channel through modeline notificaiton or tracking-next-buffer

### ISSUE THREAD

**Issue by finalpatch** [yuya373/emacs-slack#474]
**Describe the bug**

Entering channel by clicking modeline or tracking-next-buffer (C-c C-@), and read mark is not moved to cover the latest messages 

**To Reproduce**

1. receive a notification in mode line
2. click it
3. observe mark is not moved to latest message

**Backtrace**
```
Paste Backtrace if any.
Do not forget to mask confidential information. (e.g. token, message, ...)
```

**Expected behavior**

**Screenshots**

**Environment:**
 - OS: [e.g. macOS]
 - Emacs Version: [e.g. 25]
 - emacs-slack Version: [e.g. `9ffc86` (commit hash) or `20190519.716` (melpa version)]

**Additional context**

**Comment by yuya373** [comment]
dup https://github.com/yuya373/emacs-slack/issues/303

If we have a hook like `buffer-displayed-hook` in Emacs, I can fix this.
