### ISSUE TITLE
Can't authenticate with `xoxc` tokens

### ISSUE THREAD

**Issue by pigmej** [yuya373/emacs-slack#481]
**Describe the bug**
Can't connect to slack workspace where the token is `xoxc` and not `xoxo`

**Expected behavior**
When I `start-slack` then I get error auth_failed

**Screenshots**

**Environment:**
 - OS: Linux
 - Emacs Version: 26.3
 - emacs-slack Version: 20190803.1406

**Additional context**
It works ok in Ripcord

**Comment by Malabarba** [comment]
To anyone else who runs into this. I managed to obtain a valid token following these instructions: https://github.com/jackellenberger/emojme#finding-a-slack-token

**Comment by damien-biasotto** [comment]
@Malabarba comment fix this issue. probably we should update the Read me ?

**Comment by skybert** [comment]
FYI: the instructions at `https://github.com/jackellenberger/emojme#finding-a-slack-token` didn't work in Firefox Developer Edition `71.0b4 (64-bit)`, but worked like a charm in Google Chrome `76.0.3809.132`.
