### ISSUE TITLE
How to creat a multi-paragraph message?

### ISSUE THREAD

**Issue by wang-d** [yuya373/emacs-slack#486]
**Describe the bug**
In the slack web interface, I can type RET to send a message or S-RET to insert a newline and keep typing.

In emacs-slack, both RET and S-RET will send the message immediately.

How do I insert a newline?

**To Reproduce**
In any channel, type

`p 1 S-RET p 2 RET`

**Expected behavior**
I expect to send one message with the text

```
p1
p2
```

Instead I sent the two lines as separate messages.

**Environment:**
 - OS: Debian
 - Emacs Version: 26.3
 - emacs-slack Version: slack-20191019.1858

**Additional context**
Thanks for writing this!  The slack official client is ridiculous.

**Comment by jkdufair** [comment]
p1 Ctrl-j p2

**Comment by yuya373** [comment]
or <kbd>C-q</kbd> <kbd>C-j</kbd> or use `slack-message-write-another-buffer` if you want to use buffer to write message.
