### ISSUE TITLE
curl: (6) Could not resolve host: emoji.slack-edge.com

### ISSUE THREAD

**Issue by conao3** [yuya373/emacs-slack#489]
**Describe the bug**
Follow readme flow, could not complete `slack-register-team`.

**To Reproduce**
1. Require `slack`
2. Do `M-x slack-register-team` and fill questions
3. Get code like as `xxx` via browser
4. Enter `xxx` to Emacs prompt
5. See error

**Backtrace**
Could not get backtrace.
But message is here
```
Contacting host: slack.com:443
Your Token is added to kill ring.
[2019-12-18 23:19:42] [info] [conao3] Slack Websocket Is Ready!
[2019-12-18 23:19:42] [info] [conao3] Slack Channel List Updated
[2019-12-18 23:19:42] [info] [conao3] Slack Group List Updated
[2019-12-18 23:19:42] [info] [conao3] Slack Im List Updated
Failed to request slack-dnd-status-team-info: no_users_provided
[2019-12-18 23:19:42] [info] [conao3] Slack Command List Updated
Download Failed. STATUS: exit, EVENT: exited abnormally with code 6
, URL: https://emoji.slack-edge.com/TFW5BLEP6/dusty_stick/6177a62312.png, NAME: /tmp/28e2bc3c56f554cd92d9c40f91bc8c52.png, OUTPUT: curl: (6) Could not resolve host: emoji.slack-edge.com
curl: (6) Could not resolve host: emoji.slack-edge.com
curl: (6) Could not resolve host: emoji.slack-edge.com
curl: (6) Could not resolve host: emoji.slack-edge.com
curl: (6) Could not resolve host: emoji.slack-edge.com
curl: (6) Could not resolve host: emoji.slack-edge.com
curl: (6) Could not resolve host: emoji.slack-edge.com
curl: (6) Could not resolve host: emoji.slack-edge.com

Failed to request slack-client-counts: not_allowed_token_type
Mark set [2 times]
...
```

**Expected behavior**
Ensure complete configure without any errors.

**Screenshots**
No

**Environment:**
 - OS: Linux
 - Emacs Version: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.12) of 2019-10-26
 - emacs-slack Version: 20191125.1543

**Additional context**
- I'm not using any proxies.
- emoji.slack-edge.com is reachable via ping and curl.
```
$ ping emoji.slack-edge.com
PING d7mmjxgv8shw1.cloudfront.net (13.224.161.6) 56(84) bytes of data.
64 bytes from server-13-224-161-6.hkg54.r.cloudfront.net (13.224.161.6): icmp_seq=1 ttl=238 time=66.6 ms
64 bytes from server-13-224-161-6.hkg54.r.cloudfront.net (13.224.161.6): icmp_seq=2 ttl=238 time=67.0 ms

$ curl emoji.slack-edge.com
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```

**Comment by prosoitos** [comment]
I am getting those error messages (functionality doesn't seem affected), but I had to disable these messages from the mini-buffer as it was disruptive to have them show all the time.

As this is an old issue that got resolved, I am wondering whether the problem resurfaced (or maybe I am missing something on my end)?

Thank you!

**Comment by cjennings** [comment]
@prosoitos Would you share how you disabled the error messages from the mini-buffer?

**Comment by prosoitos** [comment]
My method is totally haphazard and non satisfying. I disabled the error message that was the most annoying in my init file with:

```elisp
(let ((inhibit-message t))
  (message "curl: (6) Could not resolve host: emoji.slack-edge.com"))
```

But sometimes I get the error message at boot and moving these lines at the top of my init file doesn't help. It also of course doesn't help with all the other error messages that I get from emacs-slack whenever there are connection issues.

So this is really not great and if there were a way, within the emacs-slack config, to disable all error messages, that would be a lot better. Maybe I should open a feature request...

**Comment by prosoitos** [comment]
I kept having the problem despite my ugly method above.

In the source code, it appeared that these error messages are triggered by the function `slack-curl-downloader` in slack.request.el.

To stop having them, I redefined that function in my init file. Since I use `use-package`, I have this:

```el
(use-package slack
  :config
  (cl-defun slack-curl-downloader (url name &key (success nil) (error nil) (token nil))
    (cl-labels
	((sentinel (proc event)
                   (cond
                    ((string-equal "finished\n" event)
                     (when (functionp success) (funcall success)))
                    (t
                     (let ((status (process-status proc))
                           (output (with-current-buffer (process-buffer proc)
                                     (buffer-substring-no-properties (point-min)
                                                                     (point-max)))))
                       (if (functionp error)
			   (ignore))
		       (if (file-exists-p name)
                           (delete-file name))
		       (delete-process proc))))))
      (let* ((url-obj (url-generic-parse-url url))
	     (need-token-p (and url-obj
				(string-match-p "slack" (url-host url-obj))))
	     (proc (apply #'start-process
                          "slack-curl-downloader"
                          "slack-curl-downloader"
                          (executable-find "curl")
                          "--silent"
                          "--show-error"
                          "--fail"
                          "--location"
                          "--output" name
                          "--url" url
                          (when (and token need-token-p (string-prefix-p "https" url))
                            `("-H" ,(format "Authorization: Bearer %s" token))))))
	(set-process-sentinel proc #'sentinel)))))
```

This finally solved this ongoing annoyance.

I hope this helps.
