### ISSUE TITLE
For private organizations legacy tokens no longer work

### ISSUE THREAD

**Issue by blandest** [yuya373/emacs-slack#516]
**The TS global variable is no longer defined**
I have been using the TS global variable to read the Slack token as described in the documentation but this variable is no longer defined. This happened in the last couple of days but only for private organizations, slack.com is still defining this JavaScript variable.

**To Reproduce**
1. Go to https://slack.com/....
2. Open debugging console (F12)
3. Type in TS
4. See error "ReferenceError: TS is not defined" in Firefox. Similar in Google Chrome.

**Additional context**
It appears that the xoxs-* token is a legacy token. While it seems to be still available on slack.com, it is not for my organization.

**Comment by blandest** [comment]
What seems to have happened is that the main Slack page is no longer using the TS Javscript variable.

I managed to obtain the xoxs token at: https://my.slack.com/customize.

Can you please update the documentation?

**Comment by chasecaleb** [comment]
I realize this issue is closed, but just in case anyone else stumbles upon this in the future it is already documented at https://github.com/yuya373/emacs-slack#how-to-get-token
