### ISSUE TITLE
Does not take spacemacs config into account

### ISSUE THREAD

**Issue by MrMic** [yuya373/emacs-slack#518]
Hi,

I got all the requirements: token, client-id ...
and put them into spacemacs/user-config()
But when I press: SPC-a-C, it should connect directly to 
slack and give me authentication. But it is not the case, 
I still need to enter by hand: Team Name, and Token 
The same that are in my spacemacs config file ....

Very annoying. Useless for the moment.

Can you fix it or help me?
Rgds,

**Comment by yuya373** [comment]
Please write steps to reproduce the behavior

**Comment by MrMic** [comment]
Son of bitch
You close the bug like that u do  NOT  to do anything
Re-open Bastard
Nothing is fixed !!!
and Every step r explain
Read if u how how, fucking idiot
