### ISSUE TITLE
Slack im-open does nothing

### ISSUE THREAD

**Issue by cvanelteren** [yuya373/emacs-slack#535]
**Describe the bug**
Selecting a direct message does not open anything

**To Reproduce**
1. M-x slack-im-open
2. click team
3. click person "John"
4. nothing opens 

**Backtrace**
No error produced. 

**Expected behavior**
Expected buffer with private messages between colleagues

**Screenshots**

**Environment:**
 - OS:   5.8.11-1-MANJARO 
 - Emacs Version: 27.1
 - emacs-slack Version: 29299830.1021

**Additional context**
Seeing messages from channels work just fine.

**Comment by cvanelteren** [comment]
Magically it started working today. Not sure what changed...

**Comment by ctaque** [comment]
Facing the same issue 
- Emacs 28.1
- unknown emacs slack version
- OS ubuntu 20.04
