### ISSUE TITLE
API tokens have changed and can no longer be acquired.

### ISSUE THREAD

**Issue by EricGebhart** [yuya373/emacs-slack#540]
The directions for acquiring a personal token no longer work,
and the API tokens are no longer being created.

Follow the directions in the readme.  The TS namespace no longer exists
on the customize page.   Researching further, these tokens are deprecated
and are no longer being created.

I used emacs-slack before, in the beginning, But I no longer know what my 
token was, or that it would work now anyway.

I don't know if this means that slack.el no longer works at all or if there is
something else to do.  Slack has changed their API for apps.

 - OS: Arch Linux
 - Emacs Version: 27

**Comment by ryanprior** [comment]
I just tried it and the instructions still work for me. Maybe Slack is rolling this change out incrementally, or maybe your customize page is unusual somehow?

**Comment by EricGebhart** [comment]
I'm not sure I'll try again in a bit. I know it worked before. Envoyé depuis ma tablette Huawei-------- Message original --------De : Ryan Prior <notifications@github.com>Date : mar. 24 nov. 2020 à 18:59À : yuya373/emacs-slack <emacs-slack@noreply.github.com>Cc : Eric Gebhart <e.a.gebhart@gmail.com>, Author <author@noreply.github.com>Objet : Re: [yuya373/emacs-slack] API tokens have changed and can no longer be acquired. (#540)
I just tried it and the instructions still work for me. Maybe Slack is rolling this change out incrementally, or maybe your customize page is unusual somehow?

**Comment by EricGebhart** [comment]
Ok. I got it working. I don't know what was happening before.  I managed to get my tokens.

**Comment by worldofgeese** [comment]
I can't get a token in Firefox.

**Comment by andrewnaguib** [comment]
Hello @EricGebhart, how did you manage to obtain your token. I'm on Arch too; instructions are not working for me.

**Comment by EricGebhart** [comment]
Yes I did. I think what I was doing wromg was doing the process at the top level of my account. But that doesn't work. I have multiple slacks. I needed to go to each Slack team and do that process for each one. Hope that helps, EritEnvoyé depuis ma tablette Huawei-------- Message original --------De : Andrew Naguib <notifications@github.com>Date : mer. 6 janv. 2021 à 04:59À : yuya373/emacs-slack <emacs-slack@noreply.github.com>Cc : Eric Gebhart <e.a.gebhart@gmail.com>, Mention <mention@noreply.github.com>Objet : Re: [yuya373/emacs-slack] API tokens have changed and can no longer be acquired. (#540)
Hello @EricGebhart, how did you manage to obtain your token. I'm on Arch too; instructions are not working for me.
