### ISSUE TITLE
Error (websocket): in callback `on-message': error: "Invalid search bound (wrong side of point)"

### ISSUE THREAD

**Issue by kostajh** [yuya373/emacs-slack#55]
Sent a direct message to an offline user containing a link, and got this error (the message sent successfully).

```
Error (websocket): in callback `on-message': error: "Invalid search bound (wrong side of point)"
```

**Comment by kostajh** [comment]
Got this again when sending a DM to an online user, again with a link contained in the message.

**Comment by yuya373** [comment]
please eval `(setq websocket-callback-debug-on-error t)` and show me backtrace.

**Comment by yuya373** [comment]
Are you using `emoji-cheat-sheet-plus`?
I got this error when using it.

**Comment by kostajh** [comment]
yep

Yuya Minami writes:

> Are you using `emoji-cheat-sheet-plus`?
> I got this error when using it.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/yuya373/emacs-slack/issues/55#issuecomment-176807863


-- 
@kostajh | kosta@kostaharlan.net

**Comment by yuya373** [comment]
will be fixed with this https://github.com/syl20bnr/emacs-emoji-cheat-sheet-plus/pull/4
