### ISSUE TITLE
Provide warning when sending message and no connection to Slack is open

### ISSUE THREAD

**Issue by kostajh** [yuya373/emacs-slack#57]
I was connected to Slack on my laptop, closed it, walked up a few floors and re-opened. Then I typed out a message in a Slack buffer and hit enter. The message disappeared (unrecoverable?) and wasn't sent. It would be good to:

- Prevent input when there's no connection to Slack
- Attempt to send, if no connection, try to connect and preserve the message in the input buffer
- Other ideas?

**Comment by ryuslash** [comment]
Another idea might be to show a message with a specific face telling you that the message couldn't be sent?

Wasn't the message still recoverable by pressing `M-p` at the prompt? lui.el provides input history, but I don't know if it is only saved after successfully sending a message.
