### ISSUE TITLE
"OAuth error: invalid_client_id"

### ISSUE THREAD

**Issue by tomb7890** [yuya373/emacs-slack#59]
Hi! I am wondering if someone can help me with this error I'm getting from Firefox when I try to fire up emacs-slack. Looks like a likely configuration problem but I have double and triple checked the oauth credentials. I've put a scrambled copy of my config up here. 

  https://gist.github.com/tomb7890/27da3bc955870ebf0589

I'm using Emacs 24.4.1. Had no problems installing the prerequisite packages, as far as I can tell. Had no problems getting my id etc. from slack.com as far as I can tell. 

Thanks

**Comment by yuya373** [comment]
Hi!

if you set `slack-token` before complete `slack-start`, try to set `slack-token` to nil and invoke `slack-start`.
set `slack-token` after complete `slack-start` to shortcut some authorization step.
once authorization completed, set `slack-token` with token supplied from slack.com.

**Comment by tomb7890** [comment]
Thanks - still getting same error from Firefox on invoking slack-start, after having done (setq slack-token nil).  I don't know if this is related but I believe the following only started happening after I started installing and configuring emacs-slack:  
'Error (el-get): while installing package: El-get can not find a recipe for package "package"'
I do see however a lot of files in .emacs.d/elpa/slack-20160129.715

**Comment by yuya373** [comment]
Ok, according to slack document, client_id is invalid.
https://api.slack.com/methods/oauth.access

**Comment by tomb7890** [comment]
Thank for your help Yuya. I seem to have things working now, although I continue to get the very same client_id error from Firefox.  After setting the token late, as you suggested, I am now able to get into Slack and send and receive messages.

**Comment by yuya373** [comment]
:tada:
