### ISSUE TITLE
Multiple team support

### ISSUE THREAD

**Issue by tadfisher** [yuya373/emacs-slack#61]
The official client allows selecting from more than one Slack team. ERC and rcirc, popular Emacs IRC clients, provide similar features by supporting more than one IRC server connection.

Skimming the source, a path forward may be to define a `slack-team` structure and nest most of the vars in `slack.el` under that. A `slack-teams-alist` could then hold the list of teams available for connection.

The drudge work, then, is modifying almost every function to require a `team` argument, and provide wrappers for interactive functions which select the `team` from the current buffer, or add a completing-read for picking from `slack-teams-alist` interactively.

If this is a good direction to go, I'd be happy to tackle this.

**Comment by tadfisher** [comment]
Another option is to emulate ERC, where the main entry point is a `slack` function that takes all connection parameters as keyword arguments, and the client internally maintains the mapping between team and buffer. Doesn't materially change the approach above, but it's cleaner from a configuration perspective.

**Comment by yuya373** [comment]
I don't know much about ERC and I don't understand second option.
Is there sample code about ERC?

**Comment by capitaomorte** [comment]
I hope I'm not intruding with this plug, but I'm developing a slack client
for emacs myself which supports this feature. Its still experimental and
undocumented (there's not even a readme yet), but perhaps the two efforts
can be joined somehow. Find it at https://github.com/capitaomorte/eslack

**Comment by yuya373** [comment]
@capitaomorte thanks!
.

**Comment by yuya373** [comment]
I implemented multiple team feature in [this branch](https://github.com/yuya373/emacs-slack/tree/multiple-team).
I'd appreciate give me any feedback for this.
