### ISSUE TITLE
slack-room-load-prev-messages fails with wrong-type-argument integer-or-marker-p nil

### ISSUE THREAD

**Issue by muhvit** [yuya373/emacs-slack#62]
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  get-text-property(nil ts)
  slack-room-load-prev-messages()
  call-interactively(slack-room-load-prev-messages record nil)
  command-execute(slack-room-load-prev-messages record)
  execute-extended-command(nil "slack-room-load-prev-messages")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by yuya373** [comment]
this might be fixed by 634a4b227e72c6171bd9065ffe5a01f7af465403
