### ISSUE TITLE
upon slack-im-select: "Invalid function: slack-buffer-widen"

### ISSUE THREAD

**Issue by zck** [yuya373/emacs-slack#76]
Sometimes, when I have more than one window open in Emacs (that is, the frame is split), and I run `slack-im-select`, I get an error in the minibuffer: `Invalid function: slack-buffer-widen`.

If I open up slack-buffer.el, and move `slack-buffer-widen` *before* its first usage, I don't get the flycheck error. But I'm not sure if this is a real fix; the [Emacs macro documentation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Compiling-Macros.html#Compiling-Macros) says:

> In order for compilation of macro calls to work, the macros must already be defined in Lisp when the calls to them are compiled. The compiler has a special feature to help you do this: if a file being compiled contains a defmacro form, the macro is defined temporarily for the rest of the compilation of that file. 

So perhaps this isn't the issue. I don't see this problem when I have only one window open.

**Comment by yuya373** [comment]
I can't reproduce this bug, according to document move up macro definition.
Thanks!
