### ISSUE TITLE
No obvious way to open a new Direct Message

### ISSUE THREAD

**Issue by zck** [yuya373/emacs-slack#77]
If I've already been talking with someone on slack, `slack-im-select` allows me to open up my chat with that person.

But if I haven't talked to someone before, I'm not sure how I can talk to them. They don't show up in the list for `slack-im-select`, and typing their name results in emacs-slack saying "no match".

How can I do this?

**Comment by yuya373** [comment]
`slack-im-list-update` might help. It reload available direct message channel and user list.
Slack send event when new member joined and have api to explicit open and close direct message channel, so I'll implement these in this weekend.

**Comment by zck** [comment]
Thanks!
