### ISSUE TITLE
Suggestion: moving commands

### ISSUE THREAD

**Issue by supermomonga** [yuya373/emacs-slack#89]
# Problem

Each message has multiple lines (name and time, message, blank line for separator), so we have to press up or down key at least 3 times to focus to the next or previous message.

# Suggestion

Maybe we need following commands (and functions used by their commands) to move between each messages.

- `slack-messages-move-to-next-message`
  - The command to move to the next (below one) message in the buffer that determined by current cursor position.
- `slack-messages-move-to-previous-message`
  - The command to move to the previous (above one) message in the buffer that determined by current cursor position.
- `slack-messages-move-to-first-message`
  - The command to move to the first (top) message in the buffer
- `slack-messages-move-to-last-message`
  - The command to move to the last (bottom) message in the buffer

What do you think?

**Comment by yuya373** [comment]
I didn't think that until implement ( #91 ) these functions, actually these are useful.
`evil-mode`'s "gg" and "G" take place moving first and last message functions, though. ;)
really appreciated for this suggestion!

**Comment by supermomonga** [comment]
Awesome!
Thank you 🎉
