### ISSUE TITLE
Submitting an edited message doesn't work

### ISSUE THREAD

**Issue by skybert** [yuya373/emacs-slack#92]
Hi,

there seems to be a regression when submitting an edited message.

Editing one of my messages with `slack-message-edit` brings up the message in a buffer for edit. After making my edit and hitting `C-c C-c` I get the following error:
```
ad-Advice-call-interactively: Wrong type argument: commandp, slack-message-send-edited
```

GNU Emacs 25.1.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-05-06
emacs-slack version: 20160517.1009 (installed from melpa)

Cheers,

-Torstein

**Comment by yuya373** [comment]
thanks for reporting!

**Comment by skybert** [comment]
You're welcome. And thanks for fixing it so quickly!
