### ISSUE TITLE
All chat messages are displayed in the minibuffer

### ISSUE THREAD

**Issue by skybert** [yuya373/emacs-slack#94]
All  the chat messages are displayed in the minibuffer when I'm visiting a different buffer. This is rather annoying and I would like to turn it off (is this a bug or a feature?)

My slack settings are:

```
(require 'slack)
(setq slack-enable-emoji t
      slack-buffer-emojify nil
      slack-typing-visibility 'buffer
      slack-prefer-current-team t)
```

Best regards,

-Torstein

```
emacs-slack-20160521.722 (via melpa)
GNU Emacs 25.1.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.20.4) of 2016-05-24
```

**Comment by vspinu** [comment]
Same here.

**Comment by yuya373** [comment]
I'm not sure `All the chat messages` meaning, describe current implementation.

- direct message, group message, subscribing channel or private channel (if your configure like below, test-rename and rrrrr) and messages including your name in body are notified by alert.

```
 (slack-register-team
   :name "emacs-slack"
   :default t
   :client-id "aaaaaaaaaaa.00000000000"
   :client-secret "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
   :token "aaaa-sssssssssss-88888888888-hhhhhhhhhhh-jjjjjjjjjj"
   :subscribed-channels '(test-rename rrrrr))
```

- And notification is executed regardless of buffer you are visiting.

**Comment by skybert** [comment]
@yuya373  that might explain it! I thought `:subscribed-channels` would make these channels automatically appear/open up a buffer when I logged on and I've been wondering why no channel did so. So *that's* what that settings for: getting alerts in the minibuffer.

Guess it's may bad for not reading the documentation properly.

**Comment by vspinu** [comment]
> Guess it's may bad for not reading the documentation properly. 

Where is the doc? I don't see any. If `:subscribed-channels` is intended to show messages, then it's definitely a misnomer. 

Regardless of the `:subscribed-channels` settings I see messages in the minibuffer even when my chat is the current window. I think this is redundant and with multi-line messages it's even disruptive.

**Comment by skybert** [comment]
> Where is the doc? I don't see any. 
Through the Emacs doc system:
```
C-h f slack-register-team
```
gives:  https://github.com/yuya373/emacs-slack/blob/master/slack-team.el#L92

It would have been great with some note in the `README.md`, though.

**Comment by technomancy** [comment]
I agree that this is really misleading. I thought that `:subscribed-channels` would function more like ERC's `erc-autojoin-channels-alist`, and I was really confused when I got echo area messages for every single time someone started typing.
